/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsidaug8.jiit.ac.in)
#  Generated on:      Mon Jun 30 11:21:27 2025
#  Design:            traffic_light_ctrl
#  Command:           saveNetlist traffic_light_ctrl_WEEK_3_NETLIST.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:50:47 IST (Jun 20 2025 05:20:47 UTC)
// Verification Directory fv/traffic_light_ctrl 
module traffic_light_ctrl (
	clk, 
	rst, 
	ped, 
	light, 
	walk);
   input clk;
   input rst;
   input ped;
   output [1:0] light;
   output walk;

   // Internal wires
   wire [3:0] timer;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;

   DFFRHQX4 \light_reg[1]  (.CK(clk),
	.D(n_21),
	.Q(light[1]),
	.RN(n_26));
   OAI32XL g688 (.A0(n_16),
	.A1(n_23),
	.A2(n_12),
	.B0(n_22),
	.B1(n_1),
	.Y(n_25));
   OAI32XL g686 (.A0(n_23),
	.A1(n_10),
	.A2(n_20),
	.B0(n_22),
	.B1(n_2),
	.Y(n_24));
   AO22X1 g689 (.A0(light[1]),
	.A1(n_20),
	.B0(n_23),
	.B1(n_19),
	.Y(n_21));
   INVXL g691 (.A(n_20),
	.Y(n_22));
   OAI221XL g693 (.A0(timer[2]),
	.A1(n_19),
	.B0(timer[0]),
	.B1(n_14),
	.C0(n_17),
	.Y(n_20));
   OAI31XL g695 (.A0(n_13),
	.A1(n_23),
	.A2(n_7),
	.B0(n_11),
	.Y(n_18));
   OAI31XL g700 (.A0(timer[3]),
	.A1(n_16),
	.A2(n_8),
	.B0(timer[2]),
	.Y(n_17));
   OAI221XL g694 (.A0(n_3),
	.A1(n_14),
	.B0(timer[0]),
	.B1(n_13),
	.C0(n_12),
	.Y(n_15));
   AO21X2 g696 (.A0(timer[0]),
	.A1(n_5),
	.B0(n_0),
	.Y(n_11));
   INVXL g697 (.A(n_10),
	.Y(n_12));
   NOR2BXL g698 (.AN(n_4),
	.B(timer[1]),
	.Y(n_19));
   NOR2BXL g699 (.AN(n_6),
	.B(timer[1]),
	.Y(n_10));
   INVXL g705 (.A(n_8),
	.Y(n_9));
   INVXL g702 (.A(n_6),
	.Y(n_7));
   XNOR2X1 g703 (.A(timer[1]),
	.B(timer[2]),
	.Y(n_5));
   XNOR2X1 g704 (.A(timer[0]),
	.B(timer[3]),
	.Y(n_4));
   NOR2BXL g706 (.AN(timer[0]),
	.B(n_13),
	.Y(n_8));
   OR2X1 g709 (.A(timer[1]),
	.B(n_23),
	.Y(n_14));
   NOR2BXL g708 (.AN(timer[0]),
	.B(timer[3]),
	.Y(n_6));
   INVXL g715 (.A(ped),
	.Y(n_16));
   INVXL g711 (.A(rst),
	.Y(n_26));
   DFFRX4 walk_reg (.CK(clk),
	.D(n_24),
	.Q(walk),
	.QN(n_2),
	.RN(n_26));
   DFFRX4 \light_reg[0]  (.CK(clk),
	.D(n_25),
	.Q(light[0]),
	.QN(n_1),
	.RN(n_26));
   DFFRX4 \timer_reg[3]  (.CK(clk),
	.D(n_18),
	.Q(timer[3]),
	.QN(n_0),
	.RN(n_26));
   DFFRX4 \timer_reg[0]  (.CK(clk),
	.D(n_3),
	.Q(timer[0]),
	.QN(n_3),
	.RN(n_26));
   DFFRX4 \timer_reg[1]  (.CK(clk),
	.D(n_15),
	.Q(timer[1]),
	.QN(n_13),
	.RN(n_26));
   SDFFRX4 \timer_reg[2]  (.CK(clk),
	.D(n_23),
	.Q(timer[2]),
	.QN(n_23),
	.RN(n_26),
	.SE(n_9),
	.SI(timer[2]));
endmodule

