
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:18:38 IST (Jun 20 2025 04:48:38 UTC)

// Verification Directory fv/comparator_4bit 

module comparator_4bit(a, b, gt, lt, eq);
  input [3:0] a, b;
  output gt, lt, eq;
  wire [3:0] a, b;
  wire gt, lt, eq;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_15, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_39, n_41;
  AND3X1 g472(.A (n_8), .B (n_9), .C (n_22), .Y (eq));
  OA21X1 g468(.A0 (n_18), .A1 (n_23), .B0 (n_21), .Y (n_25));
  OAI31XL g471(.A0 (n_2), .A1 (a[0]), .A2 (n_11), .B0 (n_13), .Y
       (n_24));
  OAI31XL g470(.A0 (n_0), .A1 (b[0]), .A2 (n_41), .B0 (n_10), .Y
       (n_23));
  NOR4BXL g475(.AN (n_21), .B (n_20), .C (n_19), .D (n_18), .Y (n_22));
  INVXL g478(.A (n_15), .Y (n_21));
  INVXL g473(.A (n_41), .Y (n_13));
  INVXL g474(.A (n_10), .Y (n_11));
  XNOR2X1 g476(.A (b[0]), .B (a[0]), .Y (n_9));
  OR2X1 g485(.A (b[1]), .B (n_7), .Y (n_10));
  NOR2BXL g487(.AN (n_3), .B (n_4), .Y (n_20));
  NOR2BXL g486(.AN (n_5), .B (n_6), .Y (n_18));
  XNOR2X1 g477(.A (b[1]), .B (a[1]), .Y (n_8));
  NOR2BXL g481(.AN (n_6), .B (n_5), .Y (n_15));
  NOR2BXL g482(.AN (n_4), .B (n_3), .Y (n_19));
  INVXL g495(.A (b[0]), .Y (n_2));
  INVXL g489(.A (b[3]), .Y (n_3));
  INVXL g488(.A (a[2]), .Y (n_6));
  INVXL g494(.A (a[1]), .Y (n_7));
  INVXL g491(.A (a[0]), .Y (n_0));
  INVXL g492(.A (b[2]), .Y (n_5));
  INVXL g493(.A (a[3]), .Y (n_4));
  AOI2BB1X4 g2(.A0N (n_19), .A1N (n_39), .B0 (n_20), .Y (lt));
  AOI2BB1X4 g496(.A0N (n_15), .A1N (n_24), .B0 (n_18), .Y (n_39));
  AOI2BB1X4 g497(.A0N (n_20), .A1N (n_25), .B0 (n_19), .Y (gt));
  CLKAND2X12 g498(.A (n_7), .B (b[1]), .Y (n_41));
endmodule

