/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsidaug8.jiit.ac.in)
#  Generated on:      Mon Jun 30 11:05:59 2025
#  Design:            full_adder
#  Command:           saveNetlist full_adder_WEEK_3_NETLIST.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:36:49 IST (Jun 20 2025 05:06:49 UTC)
// Verification Directory fv/full_adder 
module full_adder (
	a, 
	b, 
	cin, 
	sum, 
	cout);
   input a;
   input b;
   input cin;
   output sum;
   output cout;

   ADDFX4 g101 (.A(b),
	.B(cin),
	.CI(a),
	.CO(cout),
	.S(sum));
endmodule

