
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:40:28 IST (Jun 20 2025 05:10:28 UTC)

// Verification Directory fv/jk_ff 

module jk_ff(j, k, clk, rst, q);
  input j, k, clk, rst;
  output q;
  wire j, k, clk, rst;
  wire q;
  wire n_0, n_1, n_2;
  INVXL g33(.A (rst), .Y (n_1));
  INVXL g31(.A (k), .Y (n_0));
  SDFFRX2 q_reg(.RN (n_1), .CK (clk), .D (n_0), .SE (n_2), .SI (j), .Q
       (q), .QN (n_2));
endmodule

