/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsidaug8.jiit.ac.in)
#  Generated on:      Mon Jun 30 11:33:27 2025
#  Design:            sequence_detector_1011
#  Command:           saveNetlist sequence_detector_1011_WEEK_3_NETLIST.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 30 2025 10:33:46 IST (Jun 30 2025 05:03:46 UTC)
// Verification Directory fv/sequence_detector_1011 
module sequence_detector_1011 (
	clk, 
	rst, 
	in, 
	detected);
   input clk;
   input rst;
   input in;
   output detected;

   // Internal wires
   wire [2:0] current_state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_9;
   wire n_10;
   wire n_11;

   AO22X1 g373 (.A0(n_6),
	.A1(n_9),
	.B0(n_3),
	.B1(n_4),
	.Y(n_11));
   AO21X2 g378 (.A0(current_state[0]),
	.A1(n_1),
	.B0(detected),
	.Y(n_9));
   NOR2BXL g375 (.AN(n_2),
	.B(n_6),
	.Y(n_7));
   NOR2BXL g376 (.AN(n_4),
	.B(n_3),
	.Y(n_5));
   AND3X1 g379 (.A(current_state[2]),
	.B(n_0),
	.C(n_3),
	.Y(detected));
   ACHCONX2 g377 (.A(current_state[2]),
	.B(current_state[1]),
	.CI(current_state[0]),
	.CON(n_2));
   AND3X1 g380 (.A(in),
	.B(current_state[1]),
	.C(n_1),
	.Y(n_4));
   INVXL g385 (.A(in),
	.Y(n_6));
   INVXL g384 (.A(rst),
	.Y(n_10));
   DFFRX4 \current_state_reg[2]  (.CK(clk),
	.D(n_5),
	.Q(current_state[2]),
	.QN(n_1),
	.RN(n_10));
   DFFRX4 \current_state_reg[1]  (.CK(clk),
	.D(n_11),
	.Q(current_state[1]),
	.QN(n_0),
	.RN(n_10));
   DFFRX4 \current_state_reg[0]  (.CK(clk),
	.D(n_7),
	.Q(current_state[0]),
	.QN(n_3),
	.RN(n_10));
endmodule

