
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:36:49 IST (Jun 20 2025 05:06:49 UTC)

// Verification Directory fv/full_adder 

module full_adder(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFX4 g101(.A (b), .B (cin), .CI (a), .CO (cout), .S (sum));
endmodule

