
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:36:48 IST (Jun 20 2025 05:06:48 UTC)

// Verification Directory fv/full_adder 

module full_adder(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  wire n_0, n_1, n_2, n_3;
  XNOR2XL g95(.A (n_2), .B (n_3), .Y (sum));
  ACHCONX2 g96(.A (n_0), .B (n_3), .CI (n_1), .CON (cout));
  XNOR2X1 g97(.A (b), .B (n_1), .Y (n_2));
  INVXL g99(.A (a), .Y (n_1));
  INVXL g100(.A (b), .Y (n_0));
  INVXL g98(.A (cin), .Y (n_3));
endmodule

