
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 19 2025 11:22:42 IST (Jun 19 2025 05:52:42 UTC)

// Verification Directory fv/ring_counter 

module ring_counter(clk, rst, q);
  input clk, rst;
  output [3:0] q;
  wire clk, rst;
  wire [3:0] q;
  wire n_0;
  DFFSHQX4 \q_reg[0] (.SN (n_0), .CK (clk), .D (q[3]), .Q (q[0]));
  DFFRHQX4 \q_reg[3] (.RN (n_0), .CK (clk), .D (q[2]), .Q (q[3]));
  DFFRHQX4 \q_reg[2] (.RN (n_0), .CK (clk), .D (q[1]), .Q (q[2]));
  DFFRHQX4 \q_reg[1] (.RN (n_0), .CK (clk), .D (q[0]), .Q (q[1]));
  INVXL g7(.A (rst), .Y (n_0));
endmodule

