
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:27:27 IST (Jun 20 2025 04:57:27 UTC)

// Verification Directory fv/binary_to_gray 

module binary_to_gray(bin, gray);
  input [3:0] bin;
  output [3:0] gray;
  wire [3:0] bin;
  wire [3:0] gray;
  wire n_0, n_1, n_2;
  assign gray[3] = bin[3];
  XNOR2XL g43(.A (n_0), .B (bin[2]), .Y (gray[2]));
  XNOR2XL g45(.A (n_2), .B (bin[1]), .Y (gray[1]));
  XNOR2XL g44(.A (n_1), .B (bin[0]), .Y (gray[0]));
  INVXL g46(.A (bin[2]), .Y (n_2));
  INVXL g48(.A (bin[1]), .Y (n_1));
  INVXL g47(.A (bin[3]), .Y (n_0));
endmodule

