
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:27:28 IST (Jun 20 2025 04:57:28 UTC)

// Verification Directory fv/binary_to_gray 

module binary_to_gray(bin, gray);
  input [3:0] bin;
  output [3:0] gray;
  wire [3:0] bin;
  wire [3:0] gray;
  assign gray[3] = bin[3];
  XOR2X4 g2(.A (bin[2]), .B (bin[1]), .Y (gray[1]));
  XOR2X4 g49(.A (bin[1]), .B (bin[0]), .Y (gray[0]));
  XOR2X4 g50(.A (bin[3]), .B (bin[2]), .Y (gray[2]));
endmodule

