
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 19 2025 10:50:15 IST (Jun 19 2025 05:20:15 UTC)

// Verification Directory fv/adder4bit 

module adder4bit(a, b, sum);
  input [3:0] a, b;
  output [4:0] sum;
  wire [3:0] a, b;
  wire [4:0] sum;
  wire n_4, n_6, n_21;
  ADDFXL g283(.A (a[3]), .B (b[3]), .CI (n_6), .CO (sum[4]), .S
       (sum[3]));
  ADDFXL g284(.A (a[2]), .B (b[2]), .CI (n_4), .CO (n_6), .S (sum[2]));
  ADDFXL g285(.A (a[1]), .B (b[1]), .CI (n_21), .CO (n_4), .S (sum[1]));
  ADDHX4 g291(.A (a[0]), .B (b[0]), .CO (n_21), .S (sum[0]));
endmodule

