/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsidaug8.jiit.ac.in)
#  Generated on:      Fri Jul 25 13:39:15 2025
#  Design:            digital_safe
#  Command:           saveNetlist digital_safe_WEEK3.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul 25 2025 12:42:24 IST (Jul 25 2025 07:12:24 UTC)
// Verification Directory fv/digital_safe 
module digital_safe (
	clk, 
	rst, 
	entered_code, 
	master_code, 
	duress_code, 
	reset_code_button, 
	new_code, 
	confirm_reset, 
	unlocked, 
	alert);
   input clk;
   input rst;
   input [31:0] entered_code;
   input [31:0] master_code;
   input [31:0] duress_code;
   input reset_code_button;
   input [31:0] new_code;
   input confirm_reset;
   output unlocked;
   output alert;

   // Internal wires
   wire [1:0] attempts;
   wire [31:0] current_code;
   wire [19:0] lock_timer;
   wire SUB_TC_OP_4_n_1140;
   wire SUB_TC_OP_4_n_1141;
   wire SUB_TC_OP_4_n_1142;
   wire SUB_TC_OP_4_n_1143;
   wire SUB_TC_OP_4_n_1144;
   wire SUB_TC_OP_4_n_1145;
   wire SUB_TC_OP_4_n_1146;
   wire SUB_TC_OP_4_n_1147;
   wire SUB_TC_OP_4_n_1148;
   wire SUB_TC_OP_4_n_1149;
   wire SUB_TC_OP_4_n_1150;
   wire SUB_TC_OP_4_n_1151;
   wire SUB_TC_OP_4_n_1152;
   wire SUB_TC_OP_4_n_1153;
   wire SUB_TC_OP_4_n_1154;
   wire SUB_TC_OP_4_n_1155;
   wire SUB_TC_OP_4_n_1156;
   wire SUB_TC_OP_4_n_1159;
   wire SUB_TC_OP_4_n_1160;
   wire SUB_TC_OP_4_n_1162;
   wire SUB_TC_OP_4_n_1163;
   wire SUB_TC_OP_4_n_1164;
   wire SUB_TC_OP_4_n_1165;
   wire SUB_TC_OP_4_n_1168;
   wire SUB_TC_OP_4_n_1169;
   wire SUB_TC_OP_4_n_1170;
   wire SUB_TC_OP_4_n_1171;
   wire SUB_TC_OP_4_n_1172;
   wire SUB_TC_OP_4_n_1173;
   wire SUB_TC_OP_4_n_1174;
   wire csa_tree_ADD_TC_OP16_groupi_n_0;
   wire csa_tree_ADD_TC_OP16_groupi_n_2;
   wire csa_tree_ADD_TC_OP16_groupi_n_3;
   wire csa_tree_ADD_TC_OP16_groupi_n_4;
   wire csa_tree_ADD_TC_OP16_groupi_n_5;
   wire csa_tree_ADD_TC_OP16_groupi_n_6;
   wire csa_tree_ADD_TC_OP16_groupi_n_7;
   wire csa_tree_ADD_TC_OP16_groupi_n_8;
   wire csa_tree_ADD_TC_OP16_groupi_n_9;
   wire csa_tree_ADD_TC_OP16_groupi_n_10;
   wire csa_tree_ADD_TC_OP16_groupi_n_11;
   wire csa_tree_ADD_TC_OP16_groupi_n_12;
   wire csa_tree_ADD_TC_OP16_groupi_n_13;
   wire csa_tree_ADD_TC_OP16_groupi_n_14;
   wire csa_tree_ADD_TC_OP16_groupi_n_15;
   wire csa_tree_ADD_TC_OP16_groupi_n_16;
   wire csa_tree_ADD_TC_OP16_groupi_n_17;
   wire csa_tree_ADD_TC_OP16_groupi_n_18;
   wire csa_tree_ADD_TC_OP16_groupi_n_19;
   wire csa_tree_ADD_TC_OP16_groupi_n_20;
   wire csa_tree_ADD_TC_OP16_groupi_n_21;
   wire csa_tree_ADD_TC_OP16_groupi_n_22;
   wire csa_tree_ADD_TC_OP16_groupi_n_23;
   wire csa_tree_ADD_TC_OP16_groupi_n_24;
   wire csa_tree_ADD_TC_OP16_groupi_n_25;
   wire csa_tree_ADD_TC_OP16_groupi_n_26;
   wire csa_tree_ADD_TC_OP16_groupi_n_27;
   wire csa_tree_ADD_TC_OP16_groupi_n_28;
   wire csa_tree_ADD_TC_OP16_groupi_n_29;
   wire csa_tree_ADD_TC_OP16_groupi_n_30;
   wire csa_tree_ADD_TC_OP16_groupi_n_31;
   wire csa_tree_ADD_TC_OP16_groupi_n_33;
   wire csa_tree_ADD_TC_OP16_groupi_n_35;
   wire csa_tree_ADD_TC_OP16_groupi_n_37;
   wire csa_tree_ADD_TC_OP16_groupi_n_39;
   wire csa_tree_ADD_TC_OP16_groupi_n_41;
   wire csa_tree_ADD_TC_OP16_groupi_n_43;
   wire csa_tree_ADD_TC_OP16_groupi_n_45;
   wire csa_tree_ADD_TC_OP16_groupi_n_47;
   wire csa_tree_ADD_TC_OP16_groupi_n_49;
   wire csa_tree_ADD_TC_OP16_groupi_n_51;
   wire csa_tree_ADD_TC_OP16_groupi_n_53;
   wire csa_tree_ADD_TC_OP16_groupi_n_55;
   wire csa_tree_ADD_TC_OP16_groupi_n_57;
   wire csa_tree_ADD_TC_OP16_groupi_n_59;
   wire csa_tree_ADD_TC_OP16_groupi_n_61;
   wire csa_tree_ADD_TC_OP16_groupi_n_63;
   wire csa_tree_ADD_TC_OP16_groupi_n_65;
   wire csa_tree_ADD_TC_OP16_groupi_n_67;
   wire csa_tree_ADD_TC_OP16_groupi_n_69;
   wire csa_tree_ADD_TC_OP16_groupi_n_71;
   wire csa_tree_ADD_TC_OP16_groupi_n_73;
   wire csa_tree_ADD_TC_OP16_groupi_n_75;
   wire csa_tree_ADD_TC_OP16_groupi_n_77;
   wire csa_tree_ADD_TC_OP16_groupi_n_79;
   wire csa_tree_ADD_TC_OP16_groupi_n_81;
   wire csa_tree_ADD_TC_OP16_groupi_n_83;
   wire csa_tree_ADD_TC_OP16_groupi_n_85;
   wire csa_tree_ADD_TC_OP16_groupi_n_87;
   wire csa_tree_ADD_TC_OP16_groupi_n_89;
   wire csa_tree_ADD_TC_OP16_groupi_n_91;
   wire csa_tree_ADD_TC_OP_2_groupi_n_0;
   wire csa_tree_ADD_TC_OP_2_groupi_n_2;
   wire csa_tree_ADD_TC_OP_2_groupi_n_3;
   wire csa_tree_ADD_TC_OP_2_groupi_n_4;
   wire csa_tree_ADD_TC_OP_2_groupi_n_5;
   wire csa_tree_ADD_TC_OP_2_groupi_n_6;
   wire csa_tree_ADD_TC_OP_2_groupi_n_7;
   wire csa_tree_ADD_TC_OP_2_groupi_n_8;
   wire csa_tree_ADD_TC_OP_2_groupi_n_9;
   wire csa_tree_ADD_TC_OP_2_groupi_n_10;
   wire csa_tree_ADD_TC_OP_2_groupi_n_11;
   wire csa_tree_ADD_TC_OP_2_groupi_n_12;
   wire csa_tree_ADD_TC_OP_2_groupi_n_13;
   wire csa_tree_ADD_TC_OP_2_groupi_n_14;
   wire csa_tree_ADD_TC_OP_2_groupi_n_15;
   wire csa_tree_ADD_TC_OP_2_groupi_n_16;
   wire csa_tree_ADD_TC_OP_2_groupi_n_17;
   wire csa_tree_ADD_TC_OP_2_groupi_n_18;
   wire csa_tree_ADD_TC_OP_2_groupi_n_19;
   wire csa_tree_ADD_TC_OP_2_groupi_n_20;
   wire csa_tree_ADD_TC_OP_2_groupi_n_21;
   wire csa_tree_ADD_TC_OP_2_groupi_n_22;
   wire csa_tree_ADD_TC_OP_2_groupi_n_23;
   wire csa_tree_ADD_TC_OP_2_groupi_n_24;
   wire csa_tree_ADD_TC_OP_2_groupi_n_25;
   wire csa_tree_ADD_TC_OP_2_groupi_n_26;
   wire csa_tree_ADD_TC_OP_2_groupi_n_27;
   wire csa_tree_ADD_TC_OP_2_groupi_n_28;
   wire csa_tree_ADD_TC_OP_2_groupi_n_29;
   wire csa_tree_ADD_TC_OP_2_groupi_n_30;
   wire csa_tree_ADD_TC_OP_2_groupi_n_31;
   wire csa_tree_ADD_TC_OP_2_groupi_n_33;
   wire csa_tree_ADD_TC_OP_2_groupi_n_35;
   wire csa_tree_ADD_TC_OP_2_groupi_n_37;
   wire csa_tree_ADD_TC_OP_2_groupi_n_39;
   wire csa_tree_ADD_TC_OP_2_groupi_n_41;
   wire csa_tree_ADD_TC_OP_2_groupi_n_43;
   wire csa_tree_ADD_TC_OP_2_groupi_n_45;
   wire csa_tree_ADD_TC_OP_2_groupi_n_47;
   wire csa_tree_ADD_TC_OP_2_groupi_n_49;
   wire csa_tree_ADD_TC_OP_2_groupi_n_51;
   wire csa_tree_ADD_TC_OP_2_groupi_n_53;
   wire csa_tree_ADD_TC_OP_2_groupi_n_55;
   wire csa_tree_ADD_TC_OP_2_groupi_n_57;
   wire csa_tree_ADD_TC_OP_2_groupi_n_59;
   wire csa_tree_ADD_TC_OP_2_groupi_n_61;
   wire csa_tree_ADD_TC_OP_2_groupi_n_63;
   wire csa_tree_ADD_TC_OP_2_groupi_n_65;
   wire csa_tree_ADD_TC_OP_2_groupi_n_67;
   wire csa_tree_ADD_TC_OP_2_groupi_n_69;
   wire csa_tree_ADD_TC_OP_2_groupi_n_71;
   wire csa_tree_ADD_TC_OP_2_groupi_n_73;
   wire csa_tree_ADD_TC_OP_2_groupi_n_75;
   wire csa_tree_ADD_TC_OP_2_groupi_n_77;
   wire csa_tree_ADD_TC_OP_2_groupi_n_79;
   wire csa_tree_ADD_TC_OP_2_groupi_n_81;
   wire csa_tree_ADD_TC_OP_2_groupi_n_83;
   wire csa_tree_ADD_TC_OP_2_groupi_n_85;
   wire csa_tree_ADD_TC_OP_2_groupi_n_87;
   wire csa_tree_ADD_TC_OP_2_groupi_n_89;
   wire csa_tree_ADD_TC_OP_2_groupi_n_91;
   wire locked;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_61;
   wire n_62;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_392;
   wire n_393;
   wire n_394;
   wire n_395;
   wire n_396;
   wire n_397;
   wire n_398;

   INVXL g1426 (.A(rst),
	.Y(n_133));
   DFFRHQX8 alert_reg (.CK(clk),
	.D(n_83),
	.Q(alert),
	.RN(n_133));
   DFFRHQX8 \attempts_reg[1]  (.CK(clk),
	.D(n_119),
	.Q(attempts[1]),
	.RN(n_133));
   SDFFRHQX4 \current_code_reg[0]  (.CK(clk),
	.D(new_code[0]),
	.Q(current_code[0]),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[0]));
   SDFFRHQX8 \current_code_reg[31]  (.CK(clk),
	.D(new_code[31]),
	.Q(current_code[31]),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[31]));
   DFFRHQX8 \lock_timer_reg[1]  (.CK(clk),
	.D(n_113),
	.Q(lock_timer[1]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[2]  (.CK(clk),
	.D(n_112),
	.Q(lock_timer[2]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[3]  (.CK(clk),
	.D(n_114),
	.Q(lock_timer[3]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[4]  (.CK(clk),
	.D(n_111),
	.Q(lock_timer[4]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[5]  (.CK(clk),
	.D(n_120),
	.Q(lock_timer[5]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[9]  (.CK(clk),
	.D(n_110),
	.Q(lock_timer[9]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[10]  (.CK(clk),
	.D(n_116),
	.Q(lock_timer[10]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[11]  (.CK(clk),
	.D(n_115),
	.Q(lock_timer[11]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[12]  (.CK(clk),
	.D(n_123),
	.Q(lock_timer[12]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[13]  (.CK(clk),
	.D(n_126),
	.Q(lock_timer[13]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[16]  (.CK(clk),
	.D(n_121),
	.Q(lock_timer[16]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[17]  (.CK(clk),
	.D(n_24),
	.Q(lock_timer[17]),
	.RN(n_133));
   DFFRHQX8 \lock_timer_reg[18]  (.CK(clk),
	.D(n_118),
	.Q(lock_timer[18]),
	.RN(n_133));
   DFFRHQX4 unlocked_reg (.CK(clk),
	.D(n_85),
	.Q(unlocked),
	.RN(n_133));
   OAI221XL g5084 (.A0(n_56),
	.A1(n_22),
	.B0(n_29),
	.B1(n_128),
	.C0(n_87),
	.Y(n_130));
   ADDHX1 g5089 (.A(n_38),
	.B(n_109),
	.CO(n_128),
	.S(n_129));
   OAI211XL g5090 (.A0(n_124),
	.A1(n_30),
	.B0(n_101),
	.C0(n_87),
	.Y(n_127));
   OR2X1 g5093 (.A(n_117),
	.B(n_86),
	.Y(n_126));
   ADDHX1 g5101 (.A(n_37),
	.B(n_100),
	.CO(n_124),
	.S(n_125));
   AO21X2 g5111 (.A0(lock_timer[12]),
	.A1(n_108),
	.B0(n_103),
	.Y(n_123));
   OAI221XL g5112 (.A0(n_88),
	.A1(n_23),
	.B0(n_31),
	.B1(n_102),
	.C0(n_87),
	.Y(n_122));
   AO21X2 g5113 (.A0(lock_timer[16]),
	.A1(n_108),
	.B0(n_97),
	.Y(n_121));
   AO21X2 g5114 (.A0(lock_timer[5]),
	.A1(n_106),
	.B0(n_100),
	.Y(n_120));
   AO21X2 g5118 (.A0(attempts[1]),
	.A1(n_105),
	.B0(n_89),
	.Y(n_119));
   AO21X2 g5119 (.A0(lock_timer[18]),
	.A1(n_104),
	.B0(n_86),
	.Y(n_118));
   XNOR2X1 g5120 (.A(lock_timer[13]),
	.B(n_22),
	.Y(n_117));
   AO22X1 g5121 (.A0(lock_timer[10]),
	.A1(n_99),
	.B0(n_20),
	.B1(n_27),
	.Y(n_116));
   AO22X1 g5122 (.A0(lock_timer[11]),
	.A1(n_99),
	.B0(n_21),
	.B1(n_27),
	.Y(n_115));
   AO22X1 g5123 (.A0(lock_timer[3]),
	.A1(n_99),
	.B0(n_70),
	.B1(n_27),
	.Y(n_114));
   AO22X1 g5124 (.A0(lock_timer[1]),
	.A1(n_99),
	.B0(n_51),
	.B1(n_27),
	.Y(n_113));
   AO22X1 g5125 (.A0(lock_timer[2]),
	.A1(n_99),
	.B0(n_67),
	.B1(n_27),
	.Y(n_112));
   AO22X1 g5126 (.A0(lock_timer[4]),
	.A1(n_99),
	.B0(n_77),
	.B1(n_27),
	.Y(n_111));
   AO22X1 g5127 (.A0(lock_timer[9]),
	.A1(n_99),
	.B0(n_90),
	.B1(n_27),
	.Y(n_110));
   NOR2BXL g5128 (.AN(n_103),
	.B(lock_timer[13]),
	.Y(n_109));
   AO21X2 g5130 (.A0(n_95),
	.A1(n_27),
	.B0(n_99),
	.Y(n_107));
   AO21X2 g5131 (.A0(n_74),
	.A1(n_27),
	.B0(n_99),
	.Y(n_106));
   AO21X2 g5132 (.A0(n_93),
	.A1(n_27),
	.B0(n_99),
	.Y(n_108));
   CLKINVX1 g5134 (.A(n_22),
	.Y(n_103));
   OR2X1 g5135 (.A(n_53),
	.B(n_27),
	.Y(n_105));
   OR2X1 g5136 (.A(n_96),
	.B(n_23),
	.Y(n_104));
   INVXL g5138 (.A(n_101),
	.Y(n_102));
   CLKINVX2 g5139 (.A(n_98),
	.Y(n_99));
   OA21X1 g5140 (.A0(n_64),
	.A1(n_18),
	.B0(n_27),
	.Y(n_97));
   OR2X1 g5141 (.A(n_84),
	.B(n_23),
	.Y(n_101));
   NOR2BXL g5142 (.AN(n_27),
	.B(n_82),
	.Y(n_100));
   OR2X1 g5143 (.A(n_27),
	.B(n_86),
	.Y(n_98));
   OR2X1 g5147 (.A(lock_timer[17]),
	.B(n_95),
	.Y(n_96));
   CLKINVX1 g5148 (.A(n_18),
	.Y(n_95));
   NOR2BXL g5151 (.AN(n_92),
	.B(lock_timer[12]),
	.Y(n_94));
   INVXL g5152 (.A(n_92),
	.Y(n_93));
   NOR2BXL g5154 (.AN(n_91),
	.B(lock_timer[11]),
	.Y(n_92));
   NOR2BXL g5157 (.AN(n_19),
	.B(lock_timer[10]),
	.Y(n_91));
   XNOR2X1 g5159 (.A(lock_timer[9]),
	.B(n_88),
	.Y(n_90));
   OAI33XL g5161 (.A0(attempts[1]),
	.A1(n_35),
	.A2(n_81),
	.B0(locked),
	.B1(n_0),
	.B2(n_79),
	.Y(n_89));
   OR2X1 g5165 (.A(lock_timer[8]),
	.B(n_84),
	.Y(n_88));
   CLKINVX2 g5166 (.A(n_87),
	.Y(n_86));
   AO21X2 g5167 (.A0(n_55),
	.A1(n_79),
	.B0(n_62),
	.Y(n_85));
   OR2X1 g5168 (.A(n_0),
	.B(n_81),
	.Y(n_87));
   AO22X1 g5169 (.A0(n_78),
	.A1(n_76),
	.B0(alert),
	.B1(n_17),
	.Y(n_83));
   OR3X1 g5170 (.A(lock_timer[7]),
	.B(lock_timer[6]),
	.C(n_82),
	.Y(n_84));
   OR2X1 g5171 (.A(lock_timer[5]),
	.B(n_74),
	.Y(n_82));
   CLKINVX1 g5172 (.A(n_81),
	.Y(n_80));
   OR2X1 g5173 (.A(n_17),
	.B(n_79),
	.Y(n_81));
   OR2X1 g5174 (.A(n_73),
	.B(n_75),
	.Y(n_79));
   AO22X1 g5175 (.A0(n_55),
	.A1(n_73),
	.B0(alert),
	.B1(n_0),
	.Y(n_78));
   XNOR2X1 g5176 (.A(lock_timer[4]),
	.B(n_69),
	.Y(n_77));
   INVXL g5177 (.A(n_75),
	.Y(n_76));
   AO22X1 g5178 (.A0(n_8),
	.A1(n_397),
	.B0(n_2),
	.B1(n_1),
	.Y(n_75));
   OR2X1 g5179 (.A(lock_timer[4]),
	.B(n_69),
	.Y(n_74));
   NOR2BXL g5180 (.AN(n_5),
	.B(n_72),
	.Y(n_73));
   OR4X1 g5181 (.A(n_217),
	.B(n_218),
	.C(n_219),
	.D(n_68),
	.Y(n_72));
   XNOR2X1 g5183 (.A(lock_timer[3]),
	.B(n_65),
	.Y(n_70));
   OR2X1 g5185 (.A(lock_timer[3]),
	.B(n_65),
	.Y(n_69));
   OR4X1 g5186 (.A(n_204),
	.B(n_208),
	.C(n_52),
	.D(n_59),
	.Y(n_68));
   XNOR2X1 g5207 (.A(lock_timer[2]),
	.B(n_47),
	.Y(n_67));
   OR4X1 g5208 (.A(n_214),
	.B(n_57),
	.C(n_215),
	.D(n_216),
	.Y(n_66));
   OA21X1 g5224 (.A0(lock_timer[12]),
	.A1(n_56),
	.B0(lock_timer[16]),
	.Y(n_64));
   OA21X1 g5226 (.A0(n_0),
	.A1(n_17),
	.B0(unlocked),
	.Y(n_62));
   OR2X1 g5227 (.A(lock_timer[2]),
	.B(n_47),
	.Y(n_65));
   OR4X1 g5228 (.A(n_392),
	.B(n_32),
	.C(n_3),
	.D(n_16),
	.Y(n_61));
   OR4X1 g5230 (.A(n_48),
	.B(n_225),
	.C(n_226),
	.D(n_50),
	.Y(n_59));
   OR4X1 g5231 (.A(n_6),
	.B(n_12),
	.C(n_34),
	.D(n_393),
	.Y(n_58));
   OR4X1 g5232 (.A(n_198),
	.B(n_199),
	.C(n_205),
	.D(n_49),
	.Y(n_57));
   CLKINVX2 g5234 (.A(n_17),
	.Y(n_55));
   CLKINVX16 g5235 (.A(n_53),
	.Y(n_54));
   OR4X1 g5237 (.A(n_206),
	.B(n_207),
	.C(n_223),
	.D(n_224),
	.Y(n_52));
   XNOR2X1 g5238 (.A(lock_timer[0]),
	.B(lock_timer[1]),
	.Y(n_51));
   OR4X1 g5241 (.A(n_211),
	.B(n_212),
	.C(n_227),
	.D(n_228),
	.Y(n_50));
   OR4X1 g5242 (.A(n_201),
	.B(n_202),
	.C(n_203),
	.D(n_213),
	.Y(n_49));
   OR3X1 g5243 (.A(lock_timer[15]),
	.B(lock_timer[13]),
	.C(lock_timer[14]),
	.Y(n_56));
   NOR2BXL g5245 (.AN(n_28),
	.B(n_394),
	.Y(n_53));
   OR4X1 g5246 (.A(n_209),
	.B(n_210),
	.C(n_221),
	.D(n_222),
	.Y(n_48));
   OR2X1 g5256 (.A(lock_timer[0]),
	.B(lock_timer[1]),
	.Y(n_47));
   INVXL g5317 (.A(n_164),
	.Y(n_34));
   INVXL g5324 (.A(n_167),
	.Y(n_32));
   NAND2BX4 g2 (.AN(n_86),
	.B(n_129),
	.Y(n_26));
   NAND2BX4 g5332 (.AN(n_86),
	.B(n_125),
	.Y(n_25));
   OAI2BB1X4 g5333 (.A0N(lock_timer[17]),
	.A1N(n_107),
	.B0(n_104),
	.Y(n_24));
   INVXL g3 (.A(n_27),
	.Y(n_23));
   AOI2BB1X4 g5334 (.A0N(lock_timer[18]),
	.A1N(n_96),
	.B0(n_28),
	.Y(n_27));
   NAND2BX4 g5335 (.AN(n_23),
	.B(n_94),
	.Y(n_22));
   XOR2X4 g5336 (.A(lock_timer[11]),
	.B(n_91),
	.Y(n_21));
   XOR2X4 g5337 (.A(lock_timer[10]),
	.B(n_19),
	.Y(n_20));
   NOR2X8 g5338 (.A(n_88),
	.B(lock_timer[9]),
	.Y(n_19));
   NOR3BX4 g5339 (.AN(n_94),
	.B(lock_timer[16]),
	.C(n_56),
	.Y(n_18));
   NAND2BX4 g5340 (.AN(locked),
	.B(n_394),
	.Y(n_17));
   NAND4X1 g5341 (.A(n_172),
	.B(n_173),
	.C(n_180),
	.D(n_181),
	.Y(n_16));
   NAND4X1 g5342 (.A(n_175),
	.B(n_176),
	.C(n_177),
	.D(n_178),
	.Y(n_15));
   NAND4X1 g5343 (.A(n_183),
	.B(n_184),
	.C(n_185),
	.D(n_186),
	.Y(n_14));
   NAND4X1 g5344 (.A(n_188),
	.B(n_189),
	.C(n_192),
	.D(n_193),
	.Y(n_13));
   NAND4X1 g5345 (.A(n_152),
	.B(n_153),
	.C(n_162),
	.D(n_163),
	.Y(n_12));
   NAND4X1 g5346 (.A(n_135),
	.B(n_136),
	.C(n_137),
	.D(n_146),
	.Y(n_11));
   NOR4BBX4 g5347 (.AN(n_147),
	.BN(n_134),
	.C(n_11),
	.D(n_398),
	.Y(n_10));
   NAND4X1 g5348 (.A(n_190),
	.B(n_191),
	.C(n_196),
	.D(n_197),
	.Y(n_9));
   AND4XL g5349 (.A(n_155),
	.B(n_154),
	.C(n_156),
	.D(n_157),
	.Y(n_8));
   NAND4X1 g5350 (.A(n_140),
	.B(n_141),
	.C(n_148),
	.D(n_149),
	.Y(n_7));
   NAND4X1 g5351 (.A(n_150),
	.B(n_151),
	.C(n_160),
	.D(n_161),
	.Y(n_6));
   NOR4XL g5352 (.A(n_229),
	.B(n_200),
	.C(n_66),
	.D(n_220),
	.Y(n_5));
   NAND4X1 g5353 (.A(n_138),
	.B(n_139),
	.C(n_142),
	.D(n_143),
	.Y(n_4));
   NAND4X1 g5354 (.A(n_168),
	.B(n_169),
	.C(n_170),
	.D(n_171),
	.Y(n_3));
   NOR4BBX1 g5355 (.AN(n_179),
	.BN(n_174),
	.C(n_15),
	.D(n_61),
	.Y(n_2));
   NOR4BBX4 g5356 (.AN(n_187),
	.BN(n_182),
	.C(n_14),
	.D(n_395),
	.Y(n_1));
   NAND2BX4 g5357 (.AN(attempts[0]),
	.B(attempts[1]),
	.Y(n_0));
   CLKINVX8 SUB_TC_OP_4_g2146 (.A(duress_code[20]),
	.Y(SUB_TC_OP_4_n_1140));
   CLKINVX8 SUB_TC_OP_4_g2147 (.A(duress_code[13]),
	.Y(SUB_TC_OP_4_n_1141));
   CLKINVX8 SUB_TC_OP_4_g2148 (.A(duress_code[9]),
	.Y(SUB_TC_OP_4_n_1142));
   CLKINVX8 SUB_TC_OP_4_g2149 (.A(duress_code[1]),
	.Y(SUB_TC_OP_4_n_1143));
   CLKINVX8 SUB_TC_OP_4_g2150 (.A(duress_code[7]),
	.Y(SUB_TC_OP_4_n_1144));
   CLKINVX8 SUB_TC_OP_4_g2151 (.A(duress_code[14]),
	.Y(SUB_TC_OP_4_n_1145));
   CLKINVX8 SUB_TC_OP_4_g2152 (.A(duress_code[15]),
	.Y(SUB_TC_OP_4_n_1146));
   CLKINVX8 SUB_TC_OP_4_g2153 (.A(duress_code[2]),
	.Y(SUB_TC_OP_4_n_1147));
   CLKINVX8 SUB_TC_OP_4_g2154 (.A(duress_code[24]),
	.Y(SUB_TC_OP_4_n_1148));
   CLKINVX8 SUB_TC_OP_4_g2155 (.A(duress_code[16]),
	.Y(SUB_TC_OP_4_n_1149));
   CLKINVX8 SUB_TC_OP_4_g2156 (.A(duress_code[5]),
	.Y(SUB_TC_OP_4_n_1150));
   CLKINVX8 SUB_TC_OP_4_g2157 (.A(duress_code[3]),
	.Y(SUB_TC_OP_4_n_1151));
   CLKINVX8 SUB_TC_OP_4_g2158 (.A(duress_code[10]),
	.Y(SUB_TC_OP_4_n_1152));
   CLKINVX8 SUB_TC_OP_4_g2159 (.A(duress_code[30]),
	.Y(SUB_TC_OP_4_n_1153));
   CLKINVX8 SUB_TC_OP_4_g2160 (.A(duress_code[29]),
	.Y(SUB_TC_OP_4_n_1154));
   CLKINVX8 SUB_TC_OP_4_g2161 (.A(duress_code[21]),
	.Y(SUB_TC_OP_4_n_1155));
   CLKINVX8 SUB_TC_OP_4_g2162 (.A(duress_code[26]),
	.Y(SUB_TC_OP_4_n_1156));
   CLKINVX8 SUB_TC_OP_4_g2164 (.A(duress_code[18]),
	.Y(SUB_TC_OP_4_n_1159));
   CLKINVX8 SUB_TC_OP_4_g2165 (.A(duress_code[4]),
	.Y(SUB_TC_OP_4_n_1160));
   CLKINVX8 SUB_TC_OP_4_g2167 (.A(duress_code[23]),
	.Y(SUB_TC_OP_4_n_1162));
   CLKINVX8 SUB_TC_OP_4_g2168 (.A(duress_code[22]),
	.Y(SUB_TC_OP_4_n_1163));
   CLKINVX8 SUB_TC_OP_4_g2169 (.A(duress_code[25]),
	.Y(SUB_TC_OP_4_n_1164));
   CLKINVX8 SUB_TC_OP_4_g2170 (.A(duress_code[11]),
	.Y(SUB_TC_OP_4_n_1165));
   CLKINVX8 SUB_TC_OP_4_g2172 (.A(duress_code[28]),
	.Y(SUB_TC_OP_4_n_1168));
   CLKINVX8 SUB_TC_OP_4_g2173 (.A(duress_code[6]),
	.Y(SUB_TC_OP_4_n_1169));
   CLKINVX8 SUB_TC_OP_4_g2174 (.A(duress_code[19]),
	.Y(SUB_TC_OP_4_n_1170));
   CLKINVX8 SUB_TC_OP_4_g2175 (.A(duress_code[12]),
	.Y(SUB_TC_OP_4_n_1171));
   CLKINVX8 SUB_TC_OP_4_g2176 (.A(duress_code[27]),
	.Y(SUB_TC_OP_4_n_1172));
   CLKINVX8 SUB_TC_OP_4_g2177 (.A(duress_code[8]),
	.Y(SUB_TC_OP_4_n_1173));
   CLKINVX8 SUB_TC_OP_4_g2178 (.A(duress_code[17]),
	.Y(SUB_TC_OP_4_n_1174));
   XNOR3XL SUB_TC_OP_4_g2 (.A(duress_code[31]),
	.B(entered_code[31]),
	.C(1'b1),
	.Y(n_229));
   XOR2X4 SUB_TC_OP_4_g2180 (.A(duress_code[0]),
	.B(entered_code[0]),
	.Y(n_198));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2158 (.A(entered_code[30]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_18),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_89),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_91),
	.S(n_196));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2159 (.A(entered_code[29]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_17),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_87),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_89),
	.S(n_195));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2160 (.A(entered_code[28]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_8),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_85),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_87),
	.S(n_194));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2161 (.A(entered_code[27]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_4),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_83),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_85),
	.S(n_193));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2162 (.A(entered_code[26]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_15),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_81),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_83),
	.S(n_192));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2163 (.A(entered_code[25]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_10),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_79),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_81),
	.S(n_191));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2164 (.A(entered_code[24]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_23),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_77),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_79),
	.S(n_190));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2165 (.A(entered_code[23]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_12),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_75),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_77),
	.S(n_189));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2166 (.A(entered_code[22]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_11),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_73),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_75),
	.S(n_188));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2167 (.A(entered_code[21]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_16),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_71),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_73),
	.S(n_187));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2168 (.A(entered_code[20]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_31),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_69),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_71),
	.S(n_186));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2169 (.A(entered_code[19]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_6),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_67),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_69),
	.S(n_185));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2170 (.A(entered_code[18]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_14),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_65),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_67),
	.S(n_184));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2171 (.A(entered_code[17]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_2),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_63),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_65),
	.S(n_183));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2172 (.A(entered_code[16]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_22),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_61),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_63),
	.S(n_182));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2173 (.A(entered_code[15]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_25),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_59),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_61),
	.S(n_181));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2174 (.A(entered_code[14]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_26),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_57),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_59),
	.S(n_180));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2175 (.A(entered_code[13]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_30),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_55),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_57),
	.S(n_179));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2176 (.A(entered_code[12]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_5),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_53),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_55),
	.S(n_178));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2177 (.A(entered_code[11]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_9),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_51),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_53),
	.S(n_177));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2178 (.A(entered_code[10]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_19),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_49),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_51),
	.S(n_176));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2179 (.A(entered_code[9]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_29),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_47),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_49),
	.S(n_175));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2180 (.A(entered_code[8]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_3),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_45),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_47),
	.S(n_174));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2181 (.A(entered_code[7]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_27),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_43),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_45),
	.S(n_173));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2182 (.A(entered_code[6]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_7),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_41),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_43),
	.S(n_172));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2183 (.A(entered_code[5]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_21),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_39),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_41),
	.S(n_171));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2184 (.A(entered_code[4]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_13),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_37),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_39),
	.S(n_170));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2185 (.A(entered_code[3]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_20),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_35),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_37),
	.S(n_169));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2186 (.A(entered_code[2]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_24),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_33),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_35),
	.S(n_168));
   ADDFXL csa_tree_ADD_TC_OP16_groupi_g2187 (.A(entered_code[1]),
	.B(csa_tree_ADD_TC_OP16_groupi_n_28),
	.CI(csa_tree_ADD_TC_OP16_groupi_n_0),
	.CO(csa_tree_ADD_TC_OP16_groupi_n_33),
	.S(n_167));
   XNOR3XL csa_tree_ADD_TC_OP16_groupi_g2 (.A(entered_code[31]),
	.B(current_code[31]),
	.C(csa_tree_ADD_TC_OP16_groupi_n_91),
	.Y(n_197));
   NOR2BX1 csa_tree_ADD_TC_OP16_groupi_g2223 (.AN(entered_code[0]),
	.B(current_code[0]),
	.Y(csa_tree_ADD_TC_OP16_groupi_n_0));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2158 (.A(entered_code[30]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_18),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_89),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_91),
	.S(n_164));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2159 (.A(entered_code[29]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_17),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_87),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_89),
	.S(n_163));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2160 (.A(entered_code[28]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_8),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_85),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_87),
	.S(n_162));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2161 (.A(entered_code[27]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_4),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_83),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_85),
	.S(n_161));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2162 (.A(entered_code[26]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_15),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_81),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_83),
	.S(n_160));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2163 (.A(entered_code[25]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_10),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_79),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_81),
	.S(n_159));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2164 (.A(entered_code[24]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_23),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_77),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_79),
	.S(n_158));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2165 (.A(entered_code[23]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_12),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_75),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_77),
	.S(n_157));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2166 (.A(entered_code[22]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_11),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_73),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_75),
	.S(n_156));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2167 (.A(entered_code[21]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_16),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_71),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_73),
	.S(n_155));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2168 (.A(entered_code[20]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_31),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_69),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_71),
	.S(n_154));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2169 (.A(entered_code[19]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_6),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_67),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_69),
	.S(n_153));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2170 (.A(entered_code[18]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_14),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_65),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_67),
	.S(n_152));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2171 (.A(entered_code[17]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_2),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_63),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_65),
	.S(n_151));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2172 (.A(entered_code[16]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_22),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_61),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_63),
	.S(n_150));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2173 (.A(entered_code[15]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_25),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_59),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_61),
	.S(n_149));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2174 (.A(entered_code[14]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_26),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_57),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_59),
	.S(n_148));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2175 (.A(entered_code[13]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_30),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_55),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_57),
	.S(n_147));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2176 (.A(entered_code[12]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_5),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_53),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_55),
	.S(n_146));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2177 (.A(entered_code[11]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_9),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_51),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_53),
	.S(n_145));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2178 (.A(entered_code[10]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_19),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_49),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_51),
	.S(n_144));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2179 (.A(entered_code[9]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_29),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_47),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_49),
	.S(n_143));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2180 (.A(entered_code[8]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_3),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_45),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_47),
	.S(n_142));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2181 (.A(entered_code[7]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_27),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_43),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_45),
	.S(n_141));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2182 (.A(entered_code[6]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_7),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_41),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_43),
	.S(n_140));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2183 (.A(entered_code[5]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_21),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_39),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_41),
	.S(n_139));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2184 (.A(entered_code[4]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_13),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_37),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_39),
	.S(n_138));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2185 (.A(entered_code[3]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_20),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_35),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_37),
	.S(n_137));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2186 (.A(entered_code[2]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_24),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_33),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_35),
	.S(n_136));
   ADDFXL csa_tree_ADD_TC_OP_2_groupi_g2187 (.A(entered_code[1]),
	.B(csa_tree_ADD_TC_OP_2_groupi_n_28),
	.CI(csa_tree_ADD_TC_OP_2_groupi_n_0),
	.CO(csa_tree_ADD_TC_OP_2_groupi_n_33),
	.S(n_135));
   XNOR2X1 csa_tree_ADD_TC_OP_2_groupi_g2188 (.A(master_code[0]),
	.B(entered_code[0]),
	.Y(n_134));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2190 (.A(master_code[20]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_31));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2191 (.A(master_code[13]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_30));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2192 (.A(master_code[9]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_29));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2193 (.A(master_code[1]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_28));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2194 (.A(master_code[7]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_27));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2195 (.A(master_code[14]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_26));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2196 (.A(master_code[15]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_25));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2197 (.A(master_code[2]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_24));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2198 (.A(master_code[24]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_23));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2199 (.A(master_code[16]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_22));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2200 (.A(master_code[5]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_21));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2201 (.A(master_code[3]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_20));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2202 (.A(master_code[10]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_19));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2203 (.A(master_code[30]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_18));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2204 (.A(master_code[29]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_17));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2205 (.A(master_code[21]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_16));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2206 (.A(master_code[26]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_15));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2208 (.A(master_code[18]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_14));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2209 (.A(master_code[4]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_13));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2211 (.A(master_code[23]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_12));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2212 (.A(master_code[22]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_11));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2213 (.A(master_code[25]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_10));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2214 (.A(master_code[11]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_9));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2216 (.A(master_code[28]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_8));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2217 (.A(master_code[6]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_7));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2218 (.A(master_code[19]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_6));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2219 (.A(master_code[12]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_5));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2220 (.A(master_code[27]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_4));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2221 (.A(master_code[8]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_3));
   CLKINVX8 csa_tree_ADD_TC_OP_2_groupi_g2222 (.A(master_code[17]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_2));
   NOR2BX1 csa_tree_ADD_TC_OP_2_groupi_g2223 (.AN(entered_code[0]),
	.B(master_code[0]),
	.Y(csa_tree_ADD_TC_OP_2_groupi_n_0));
   XNOR2X4 g5359 (.A(entered_code[30]),
	.B(SUB_TC_OP_4_n_1153),
	.Y(n_228));
   XNOR2X4 g5361 (.A(entered_code[29]),
	.B(SUB_TC_OP_4_n_1154),
	.Y(n_227));
   XNOR2X4 g5363 (.A(entered_code[28]),
	.B(SUB_TC_OP_4_n_1168),
	.Y(n_226));
   XNOR2X4 g5365 (.A(entered_code[27]),
	.B(SUB_TC_OP_4_n_1172),
	.Y(n_225));
   XNOR2X4 g5367 (.A(entered_code[26]),
	.B(SUB_TC_OP_4_n_1156),
	.Y(n_224));
   XNOR2X4 g5369 (.A(entered_code[25]),
	.B(SUB_TC_OP_4_n_1164),
	.Y(n_223));
   XNOR2X4 g5371 (.A(entered_code[24]),
	.B(SUB_TC_OP_4_n_1148),
	.Y(n_222));
   XNOR2X4 g5373 (.A(entered_code[23]),
	.B(SUB_TC_OP_4_n_1162),
	.Y(n_221));
   XNOR2X4 g5375 (.A(entered_code[22]),
	.B(SUB_TC_OP_4_n_1163),
	.Y(n_220));
   XNOR2X4 g5377 (.A(entered_code[21]),
	.B(SUB_TC_OP_4_n_1155),
	.Y(n_219));
   XNOR2X4 g5379 (.A(entered_code[20]),
	.B(SUB_TC_OP_4_n_1140),
	.Y(n_218));
   XNOR2X4 g5381 (.A(entered_code[19]),
	.B(SUB_TC_OP_4_n_1170),
	.Y(n_217));
   XNOR2X4 g5383 (.A(entered_code[18]),
	.B(SUB_TC_OP_4_n_1159),
	.Y(n_216));
   XNOR2X4 g5385 (.A(entered_code[17]),
	.B(SUB_TC_OP_4_n_1174),
	.Y(n_215));
   XNOR2X4 g5387 (.A(entered_code[16]),
	.B(SUB_TC_OP_4_n_1149),
	.Y(n_214));
   XNOR2X4 g5389 (.A(entered_code[15]),
	.B(SUB_TC_OP_4_n_1146),
	.Y(n_213));
   XNOR2X4 g5391 (.A(entered_code[14]),
	.B(SUB_TC_OP_4_n_1145),
	.Y(n_212));
   XNOR2X4 g5393 (.A(entered_code[13]),
	.B(SUB_TC_OP_4_n_1141),
	.Y(n_211));
   XNOR2X4 g5395 (.A(entered_code[12]),
	.B(SUB_TC_OP_4_n_1171),
	.Y(n_210));
   XNOR2X4 g5397 (.A(entered_code[11]),
	.B(SUB_TC_OP_4_n_1165),
	.Y(n_209));
   XNOR2X4 g5399 (.A(entered_code[10]),
	.B(SUB_TC_OP_4_n_1152),
	.Y(n_208));
   XNOR2X4 g5401 (.A(entered_code[9]),
	.B(SUB_TC_OP_4_n_1142),
	.Y(n_207));
   XNOR2X4 g5403 (.A(entered_code[8]),
	.B(SUB_TC_OP_4_n_1173),
	.Y(n_206));
   XNOR2X4 g5405 (.A(entered_code[7]),
	.B(SUB_TC_OP_4_n_1144),
	.Y(n_205));
   XNOR2X4 g5407 (.A(entered_code[6]),
	.B(SUB_TC_OP_4_n_1169),
	.Y(n_204));
   XNOR2X4 g5409 (.A(entered_code[5]),
	.B(SUB_TC_OP_4_n_1150),
	.Y(n_203));
   XNOR2X4 g5411 (.A(entered_code[4]),
	.B(SUB_TC_OP_4_n_1160),
	.Y(n_202));
   XNOR2X4 g5413 (.A(entered_code[3]),
	.B(SUB_TC_OP_4_n_1151),
	.Y(n_201));
   XNOR2X4 g5415 (.A(entered_code[2]),
	.B(SUB_TC_OP_4_n_1147),
	.Y(n_200));
   XNOR2X4 g5417 (.A(entered_code[1]),
	.B(SUB_TC_OP_4_n_1143),
	.Y(n_199));
   DFFRX4 \lock_timer_reg[14]  (.CK(clk),
	.D(n_26),
	.Q(lock_timer[14]),
	.QN(n_38),
	.RN(n_133));
   DFFRX4 \lock_timer_reg[6]  (.CK(clk),
	.D(n_25),
	.Q(lock_timer[6]),
	.QN(n_37),
	.RN(n_133));
   SDFFRX4 \lock_timer_reg[0]  (.CK(clk),
	.D(n_99),
	.Q(lock_timer[0]),
	.QN(n_36),
	.RN(n_133),
	.SE(n_36),
	.SI(n_27));
   SDFFRX4 \attempts_reg[0]  (.CK(clk),
	.D(n_80),
	.Q(attempts[0]),
	.QN(n_35),
	.RN(n_133),
	.SE(attempts[0]),
	.SI(n_105));
   DFFRX4 \lock_timer_reg[8]  (.CK(clk),
	.D(n_122),
	.Q(lock_timer[8]),
	.QN(n_31),
	.RN(n_133));
   DFFRX4 \lock_timer_reg[7]  (.CK(clk),
	.D(n_127),
	.Q(lock_timer[7]),
	.QN(n_30),
	.RN(n_133));
   DFFRX4 \lock_timer_reg[15]  (.CK(clk),
	.D(n_130),
	.Q(lock_timer[15]),
	.QN(n_29),
	.RN(n_133));
   DFFRX4 locked_reg (.CK(clk),
	.D(n_98),
	.Q(locked),
	.QN(n_28),
	.RN(n_133));
   SDFFSX2 \current_code_reg[20]  (.CK(clk),
	.D(new_code[20]),
	.Q(current_code[20]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_31),
	.SE(n_54),
	.SI(current_code[20]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[13]  (.CK(clk),
	.D(new_code[13]),
	.Q(current_code[13]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_30),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[13]));
   SDFFSX2 \current_code_reg[9]  (.CK(clk),
	.D(new_code[9]),
	.Q(current_code[9]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_29),
	.SE(n_54),
	.SI(current_code[9]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[1]  (.CK(clk),
	.D(new_code[1]),
	.Q(current_code[1]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_28),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[1]));
   SDFFRX4 \current_code_reg[7]  (.CK(clk),
	.D(new_code[7]),
	.Q(current_code[7]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_27),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[7]));
   SDFFSX2 \current_code_reg[14]  (.CK(clk),
	.D(new_code[14]),
	.Q(current_code[14]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_26),
	.SE(n_54),
	.SI(current_code[14]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[15]  (.CK(clk),
	.D(new_code[15]),
	.Q(current_code[15]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_25),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[15]));
   SDFFRX4 \current_code_reg[2]  (.CK(clk),
	.D(new_code[2]),
	.Q(current_code[2]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_24),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[2]));
   SDFFRX4 \current_code_reg[24]  (.CK(clk),
	.D(new_code[24]),
	.Q(current_code[24]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_23),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[24]));
   SDFFRX4 \current_code_reg[16]  (.CK(clk),
	.D(new_code[16]),
	.Q(current_code[16]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_22),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[16]));
   SDFFSX2 \current_code_reg[5]  (.CK(clk),
	.D(new_code[5]),
	.Q(current_code[5]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_21),
	.SE(n_54),
	.SI(current_code[5]),
	.SN(n_133));
   SDFFSX2 \current_code_reg[3]  (.CK(clk),
	.D(new_code[3]),
	.Q(current_code[3]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_20),
	.SE(n_54),
	.SI(current_code[3]),
	.SN(n_133));
   SDFFSX2 \current_code_reg[10]  (.CK(clk),
	.D(new_code[10]),
	.Q(current_code[10]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_19),
	.SE(n_54),
	.SI(current_code[10]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[30]  (.CK(clk),
	.D(new_code[30]),
	.Q(current_code[30]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_18),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[30]));
   SDFFRX4 \current_code_reg[29]  (.CK(clk),
	.D(new_code[29]),
	.Q(current_code[29]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_17),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[29]));
   SDFFSX2 \current_code_reg[21]  (.CK(clk),
	.D(new_code[21]),
	.Q(current_code[21]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_16),
	.SE(n_54),
	.SI(current_code[21]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[26]  (.CK(clk),
	.D(new_code[26]),
	.Q(current_code[26]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_15),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[26]));
   SDFFSX2 \current_code_reg[18]  (.CK(clk),
	.D(new_code[18]),
	.Q(current_code[18]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_14),
	.SE(n_54),
	.SI(current_code[18]),
	.SN(n_133));
   SDFFSX2 \current_code_reg[4]  (.CK(clk),
	.D(new_code[4]),
	.Q(current_code[4]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_13),
	.SE(n_54),
	.SI(current_code[4]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[23]  (.CK(clk),
	.D(new_code[23]),
	.Q(current_code[23]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_12),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[23]));
   SDFFRX4 \current_code_reg[22]  (.CK(clk),
	.D(new_code[22]),
	.Q(current_code[22]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_11),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[22]));
   SDFFSX2 \current_code_reg[25]  (.CK(clk),
	.D(new_code[25]),
	.Q(current_code[25]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_10),
	.SE(n_54),
	.SI(current_code[25]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[11]  (.CK(clk),
	.D(new_code[11]),
	.Q(current_code[11]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_9),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[11]));
   SDFFSX2 \current_code_reg[28]  (.CK(clk),
	.D(new_code[28]),
	.Q(current_code[28]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_8),
	.SE(n_54),
	.SI(current_code[28]),
	.SN(n_133));
   SDFFSX2 \current_code_reg[6]  (.CK(clk),
	.D(new_code[6]),
	.Q(current_code[6]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_7),
	.SE(n_54),
	.SI(current_code[6]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[19]  (.CK(clk),
	.D(new_code[19]),
	.Q(current_code[19]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_6),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[19]));
   SDFFSX2 \current_code_reg[12]  (.CK(clk),
	.D(new_code[12]),
	.Q(current_code[12]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_5),
	.SE(n_54),
	.SI(current_code[12]),
	.SN(n_133));
   SDFFRX4 \current_code_reg[27]  (.CK(clk),
	.D(new_code[27]),
	.Q(current_code[27]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_4),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[27]));
   SDFFRX4 \current_code_reg[8]  (.CK(clk),
	.D(new_code[8]),
	.Q(current_code[8]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_3),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[8]));
   SDFFRX4 \current_code_reg[17]  (.CK(clk),
	.D(new_code[17]),
	.Q(current_code[17]),
	.QN(csa_tree_ADD_TC_OP16_groupi_n_2),
	.RN(n_133),
	.SE(n_54),
	.SI(current_code[17]));
   XOR2X4 g5494 (.A(entered_code[0]),
	.B(current_code[0]),
	.Y(n_392));
   XOR3X1 g5495 (.A(master_code[31]),
	.B(entered_code[31]),
	.C(csa_tree_ADD_TC_OP_2_groupi_n_91),
	.Y(n_393));
   NAND2X8 g5496 (.A(reset_code_button),
	.B(confirm_reset),
	.Y(n_394));
   NAND4BBX4 g5497 (.AN(n_9),
	.BN(n_13),
	.C(n_194),
	.D(n_195),
	.Y(n_395));
   INVXL g5498 (.A(n_396),
	.Y(n_397));
   NAND4BX4 g5499 (.AN(n_58),
	.B(n_10),
	.C(n_158),
	.D(n_159),
	.Y(n_396));
   NAND4BBX4 g5500 (.AN(n_7),
	.BN(n_4),
	.C(n_144),
	.D(n_145),
	.Y(n_398));
endmodule

