###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsidaug8.jiit.ac.in)
#  Generated on:      Mon Jul  7 11:45:43 2025
#  Design:            full_adder
#  Command:           routeDesign -globalDetail
###############################################################
current_design full_adder
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
set_wire_load_mode enclosed
