
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point entered_code[31] entered_code[31] -type PI PI
add mapped point entered_code[30] entered_code[30] -type PI PI
add mapped point entered_code[29] entered_code[29] -type PI PI
add mapped point entered_code[28] entered_code[28] -type PI PI
add mapped point entered_code[27] entered_code[27] -type PI PI
add mapped point entered_code[26] entered_code[26] -type PI PI
add mapped point entered_code[25] entered_code[25] -type PI PI
add mapped point entered_code[24] entered_code[24] -type PI PI
add mapped point entered_code[23] entered_code[23] -type PI PI
add mapped point entered_code[22] entered_code[22] -type PI PI
add mapped point entered_code[21] entered_code[21] -type PI PI
add mapped point entered_code[20] entered_code[20] -type PI PI
add mapped point entered_code[19] entered_code[19] -type PI PI
add mapped point entered_code[18] entered_code[18] -type PI PI
add mapped point entered_code[17] entered_code[17] -type PI PI
add mapped point entered_code[16] entered_code[16] -type PI PI
add mapped point entered_code[15] entered_code[15] -type PI PI
add mapped point entered_code[14] entered_code[14] -type PI PI
add mapped point entered_code[13] entered_code[13] -type PI PI
add mapped point entered_code[12] entered_code[12] -type PI PI
add mapped point entered_code[11] entered_code[11] -type PI PI
add mapped point entered_code[10] entered_code[10] -type PI PI
add mapped point entered_code[9] entered_code[9] -type PI PI
add mapped point entered_code[8] entered_code[8] -type PI PI
add mapped point entered_code[7] entered_code[7] -type PI PI
add mapped point entered_code[6] entered_code[6] -type PI PI
add mapped point entered_code[5] entered_code[5] -type PI PI
add mapped point entered_code[4] entered_code[4] -type PI PI
add mapped point entered_code[3] entered_code[3] -type PI PI
add mapped point entered_code[2] entered_code[2] -type PI PI
add mapped point entered_code[1] entered_code[1] -type PI PI
add mapped point entered_code[0] entered_code[0] -type PI PI
add mapped point master_code[31] master_code[31] -type PI PI
add mapped point master_code[30] master_code[30] -type PI PI
add mapped point master_code[29] master_code[29] -type PI PI
add mapped point master_code[28] master_code[28] -type PI PI
add mapped point master_code[27] master_code[27] -type PI PI
add mapped point master_code[26] master_code[26] -type PI PI
add mapped point master_code[25] master_code[25] -type PI PI
add mapped point master_code[24] master_code[24] -type PI PI
add mapped point master_code[23] master_code[23] -type PI PI
add mapped point master_code[22] master_code[22] -type PI PI
add mapped point master_code[21] master_code[21] -type PI PI
add mapped point master_code[20] master_code[20] -type PI PI
add mapped point master_code[19] master_code[19] -type PI PI
add mapped point master_code[18] master_code[18] -type PI PI
add mapped point master_code[17] master_code[17] -type PI PI
add mapped point master_code[16] master_code[16] -type PI PI
add mapped point master_code[15] master_code[15] -type PI PI
add mapped point master_code[14] master_code[14] -type PI PI
add mapped point master_code[13] master_code[13] -type PI PI
add mapped point master_code[12] master_code[12] -type PI PI
add mapped point master_code[11] master_code[11] -type PI PI
add mapped point master_code[10] master_code[10] -type PI PI
add mapped point master_code[9] master_code[9] -type PI PI
add mapped point master_code[8] master_code[8] -type PI PI
add mapped point master_code[7] master_code[7] -type PI PI
add mapped point master_code[6] master_code[6] -type PI PI
add mapped point master_code[5] master_code[5] -type PI PI
add mapped point master_code[4] master_code[4] -type PI PI
add mapped point master_code[3] master_code[3] -type PI PI
add mapped point master_code[2] master_code[2] -type PI PI
add mapped point master_code[1] master_code[1] -type PI PI
add mapped point master_code[0] master_code[0] -type PI PI
add mapped point duress_code[31] duress_code[31] -type PI PI
add mapped point duress_code[30] duress_code[30] -type PI PI
add mapped point duress_code[29] duress_code[29] -type PI PI
add mapped point duress_code[28] duress_code[28] -type PI PI
add mapped point duress_code[27] duress_code[27] -type PI PI
add mapped point duress_code[26] duress_code[26] -type PI PI
add mapped point duress_code[25] duress_code[25] -type PI PI
add mapped point duress_code[24] duress_code[24] -type PI PI
add mapped point duress_code[23] duress_code[23] -type PI PI
add mapped point duress_code[22] duress_code[22] -type PI PI
add mapped point duress_code[21] duress_code[21] -type PI PI
add mapped point duress_code[20] duress_code[20] -type PI PI
add mapped point duress_code[19] duress_code[19] -type PI PI
add mapped point duress_code[18] duress_code[18] -type PI PI
add mapped point duress_code[17] duress_code[17] -type PI PI
add mapped point duress_code[16] duress_code[16] -type PI PI
add mapped point duress_code[15] duress_code[15] -type PI PI
add mapped point duress_code[14] duress_code[14] -type PI PI
add mapped point duress_code[13] duress_code[13] -type PI PI
add mapped point duress_code[12] duress_code[12] -type PI PI
add mapped point duress_code[11] duress_code[11] -type PI PI
add mapped point duress_code[10] duress_code[10] -type PI PI
add mapped point duress_code[9] duress_code[9] -type PI PI
add mapped point duress_code[8] duress_code[8] -type PI PI
add mapped point duress_code[7] duress_code[7] -type PI PI
add mapped point duress_code[6] duress_code[6] -type PI PI
add mapped point duress_code[5] duress_code[5] -type PI PI
add mapped point duress_code[4] duress_code[4] -type PI PI
add mapped point duress_code[3] duress_code[3] -type PI PI
add mapped point duress_code[2] duress_code[2] -type PI PI
add mapped point duress_code[1] duress_code[1] -type PI PI
add mapped point duress_code[0] duress_code[0] -type PI PI
add mapped point reset_code_button reset_code_button -type PI PI
add mapped point new_code[31] new_code[31] -type PI PI
add mapped point new_code[30] new_code[30] -type PI PI
add mapped point new_code[29] new_code[29] -type PI PI
add mapped point new_code[28] new_code[28] -type PI PI
add mapped point new_code[27] new_code[27] -type PI PI
add mapped point new_code[26] new_code[26] -type PI PI
add mapped point new_code[25] new_code[25] -type PI PI
add mapped point new_code[24] new_code[24] -type PI PI
add mapped point new_code[23] new_code[23] -type PI PI
add mapped point new_code[22] new_code[22] -type PI PI
add mapped point new_code[21] new_code[21] -type PI PI
add mapped point new_code[20] new_code[20] -type PI PI
add mapped point new_code[19] new_code[19] -type PI PI
add mapped point new_code[18] new_code[18] -type PI PI
add mapped point new_code[17] new_code[17] -type PI PI
add mapped point new_code[16] new_code[16] -type PI PI
add mapped point new_code[15] new_code[15] -type PI PI
add mapped point new_code[14] new_code[14] -type PI PI
add mapped point new_code[13] new_code[13] -type PI PI
add mapped point new_code[12] new_code[12] -type PI PI
add mapped point new_code[11] new_code[11] -type PI PI
add mapped point new_code[10] new_code[10] -type PI PI
add mapped point new_code[9] new_code[9] -type PI PI
add mapped point new_code[8] new_code[8] -type PI PI
add mapped point new_code[7] new_code[7] -type PI PI
add mapped point new_code[6] new_code[6] -type PI PI
add mapped point new_code[5] new_code[5] -type PI PI
add mapped point new_code[4] new_code[4] -type PI PI
add mapped point new_code[3] new_code[3] -type PI PI
add mapped point new_code[2] new_code[2] -type PI PI
add mapped point new_code[1] new_code[1] -type PI PI
add mapped point new_code[0] new_code[0] -type PI PI
add mapped point confirm_reset confirm_reset -type PI PI

//output ports
add mapped point unlocked unlocked -type PO PO
add mapped point alert alert -type PO PO

//inout ports




//Sequential Pins
add mapped point alert/q alert_reg/Q  -type DFF DFF
add mapped point attempts[1]/q attempts_reg[1]/Q  -type DFF DFF
add mapped point current_code[0]/q current_code_reg[0]/Q  -type DFF DFF
add mapped point current_code[31]/q current_code_reg[31]/Q  -type DFF DFF
add mapped point lock_timer[1]/q lock_timer_reg[1]/Q  -type DFF DFF
add mapped point lock_timer[2]/q lock_timer_reg[2]/Q  -type DFF DFF
add mapped point lock_timer[3]/q lock_timer_reg[3]/Q  -type DFF DFF
add mapped point lock_timer[4]/q lock_timer_reg[4]/Q  -type DFF DFF
add mapped point lock_timer[5]/q lock_timer_reg[5]/Q  -type DFF DFF
add mapped point lock_timer[9]/q lock_timer_reg[9]/Q  -type DFF DFF
add mapped point lock_timer[10]/q lock_timer_reg[10]/Q  -type DFF DFF
add mapped point lock_timer[11]/q lock_timer_reg[11]/Q  -type DFF DFF
add mapped point lock_timer[12]/q lock_timer_reg[12]/Q  -type DFF DFF
add mapped point lock_timer[13]/q lock_timer_reg[13]/Q  -type DFF DFF
add mapped point lock_timer[16]/q lock_timer_reg[16]/Q  -type DFF DFF
add mapped point lock_timer[17]/q lock_timer_reg[17]/Q  -type DFF DFF
add mapped point lock_timer[18]/q lock_timer_reg[18]/Q  -type DFF DFF
add mapped point unlocked/q unlocked_reg/Q  -type DFF DFF
add mapped point lock_timer[14]/q lock_timer_reg[14]/Q  -type DFF DFF
add mapped point lock_timer[14]/q lock_timer_reg[14]/QN  -type DFF DFF
add mapped point lock_timer[6]/q lock_timer_reg[6]/Q  -type DFF DFF
add mapped point lock_timer[6]/q lock_timer_reg[6]/QN  -type DFF DFF
add mapped point lock_timer[0]/q lock_timer_reg[0]/Q  -type DFF DFF
add mapped point lock_timer[0]/q lock_timer_reg[0]/QN  -type DFF DFF
add mapped point attempts[0]/q attempts_reg[0]/Q  -type DFF DFF
add mapped point attempts[0]/q attempts_reg[0]/QN  -type DFF DFF
add mapped point lock_timer[8]/q lock_timer_reg[8]/Q  -type DFF DFF
add mapped point lock_timer[8]/q lock_timer_reg[8]/QN  -type DFF DFF
add mapped point lock_timer[7]/q lock_timer_reg[7]/Q  -type DFF DFF
add mapped point lock_timer[7]/q lock_timer_reg[7]/QN  -type DFF DFF
add mapped point lock_timer[15]/q lock_timer_reg[15]/Q  -type DFF DFF
add mapped point lock_timer[15]/q lock_timer_reg[15]/QN  -type DFF DFF
add mapped point locked/q locked_reg/Q  -type DFF DFF
add mapped point locked/q locked_reg/QN  -type DFF DFF
add mapped point current_code[20]/q current_code_reg[20]/Q  -type DFF DFF
add mapped point current_code[20]/q current_code_reg[20]/QN  -type DFF DFF
add mapped point current_code[13]/q current_code_reg[13]/Q  -type DFF DFF
add mapped point current_code[13]/q current_code_reg[13]/QN  -type DFF DFF
add mapped point current_code[9]/q current_code_reg[9]/Q  -type DFF DFF
add mapped point current_code[9]/q current_code_reg[9]/QN  -type DFF DFF
add mapped point current_code[1]/q current_code_reg[1]/Q  -type DFF DFF
add mapped point current_code[1]/q current_code_reg[1]/QN  -type DFF DFF
add mapped point current_code[7]/q current_code_reg[7]/Q  -type DFF DFF
add mapped point current_code[7]/q current_code_reg[7]/QN  -type DFF DFF
add mapped point current_code[14]/q current_code_reg[14]/Q  -type DFF DFF
add mapped point current_code[14]/q current_code_reg[14]/QN  -type DFF DFF
add mapped point current_code[15]/q current_code_reg[15]/Q  -type DFF DFF
add mapped point current_code[15]/q current_code_reg[15]/QN  -type DFF DFF
add mapped point current_code[2]/q current_code_reg[2]/Q  -type DFF DFF
add mapped point current_code[2]/q current_code_reg[2]/QN  -type DFF DFF
add mapped point current_code[24]/q current_code_reg[24]/Q  -type DFF DFF
add mapped point current_code[24]/q current_code_reg[24]/QN  -type DFF DFF
add mapped point current_code[16]/q current_code_reg[16]/Q  -type DFF DFF
add mapped point current_code[16]/q current_code_reg[16]/QN  -type DFF DFF
add mapped point current_code[5]/q current_code_reg[5]/Q  -type DFF DFF
add mapped point current_code[5]/q current_code_reg[5]/QN  -type DFF DFF
add mapped point current_code[3]/q current_code_reg[3]/Q  -type DFF DFF
add mapped point current_code[3]/q current_code_reg[3]/QN  -type DFF DFF
add mapped point current_code[10]/q current_code_reg[10]/Q  -type DFF DFF
add mapped point current_code[10]/q current_code_reg[10]/QN  -type DFF DFF
add mapped point current_code[30]/q current_code_reg[30]/Q  -type DFF DFF
add mapped point current_code[30]/q current_code_reg[30]/QN  -type DFF DFF
add mapped point current_code[29]/q current_code_reg[29]/Q  -type DFF DFF
add mapped point current_code[29]/q current_code_reg[29]/QN  -type DFF DFF
add mapped point current_code[21]/q current_code_reg[21]/Q  -type DFF DFF
add mapped point current_code[21]/q current_code_reg[21]/QN  -type DFF DFF
add mapped point current_code[26]/q current_code_reg[26]/Q  -type DFF DFF
add mapped point current_code[26]/q current_code_reg[26]/QN  -type DFF DFF
add mapped point current_code[18]/q current_code_reg[18]/Q  -type DFF DFF
add mapped point current_code[18]/q current_code_reg[18]/QN  -type DFF DFF
add mapped point current_code[4]/q current_code_reg[4]/Q  -type DFF DFF
add mapped point current_code[4]/q current_code_reg[4]/QN  -type DFF DFF
add mapped point current_code[23]/q current_code_reg[23]/Q  -type DFF DFF
add mapped point current_code[23]/q current_code_reg[23]/QN  -type DFF DFF
add mapped point current_code[22]/q current_code_reg[22]/Q  -type DFF DFF
add mapped point current_code[22]/q current_code_reg[22]/QN  -type DFF DFF
add mapped point current_code[25]/q current_code_reg[25]/Q  -type DFF DFF
add mapped point current_code[25]/q current_code_reg[25]/QN  -type DFF DFF
add mapped point current_code[11]/q current_code_reg[11]/Q  -type DFF DFF
add mapped point current_code[11]/q current_code_reg[11]/QN  -type DFF DFF
add mapped point current_code[28]/q current_code_reg[28]/Q  -type DFF DFF
add mapped point current_code[28]/q current_code_reg[28]/QN  -type DFF DFF
add mapped point current_code[6]/q current_code_reg[6]/Q  -type DFF DFF
add mapped point current_code[6]/q current_code_reg[6]/QN  -type DFF DFF
add mapped point current_code[19]/q current_code_reg[19]/Q  -type DFF DFF
add mapped point current_code[19]/q current_code_reg[19]/QN  -type DFF DFF
add mapped point current_code[12]/q current_code_reg[12]/Q  -type DFF DFF
add mapped point current_code[12]/q current_code_reg[12]/QN  -type DFF DFF
add mapped point current_code[27]/q current_code_reg[27]/Q  -type DFF DFF
add mapped point current_code[27]/q current_code_reg[27]/QN  -type DFF DFF
add mapped point current_code[8]/q current_code_reg[8]/Q  -type DFF DFF
add mapped point current_code[8]/q current_code_reg[8]/QN  -type DFF DFF
add mapped point current_code[17]/q current_code_reg[17]/Q  -type DFF DFF
add mapped point current_code[17]/q current_code_reg[17]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
