# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Fri Jul 25 12:42:24 IST 2025

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design digital_safe

group_path -weight 1.000000 -name C2C -from [list \
  [get_cells alert_reg]  \
  [get_cells {attempts_reg[1]}]  \
  [get_cells {current_code_reg[0]}]  \
  [get_cells {current_code_reg[31]}]  \
  [get_cells {lock_timer_reg[1]}]  \
  [get_cells {lock_timer_reg[2]}]  \
  [get_cells {lock_timer_reg[3]}]  \
  [get_cells {lock_timer_reg[4]}]  \
  [get_cells {lock_timer_reg[5]}]  \
  [get_cells {lock_timer_reg[9]}]  \
  [get_cells {lock_timer_reg[10]}]  \
  [get_cells {lock_timer_reg[11]}]  \
  [get_cells {lock_timer_reg[12]}]  \
  [get_cells {lock_timer_reg[13]}]  \
  [get_cells {lock_timer_reg[16]}]  \
  [get_cells {lock_timer_reg[17]}]  \
  [get_cells {lock_timer_reg[18]}]  \
  [get_cells unlocked_reg]  \
  [get_cells {lock_timer_reg[14]}]  \
  [get_cells {lock_timer_reg[6]}]  \
  [get_cells {lock_timer_reg[0]}]  \
  [get_cells {attempts_reg[0]}]  \
  [get_cells {lock_timer_reg[8]}]  \
  [get_cells {lock_timer_reg[7]}]  \
  [get_cells {lock_timer_reg[15]}]  \
  [get_cells locked_reg]  \
  [get_cells {current_code_reg[20]}]  \
  [get_cells {current_code_reg[13]}]  \
  [get_cells {current_code_reg[9]}]  \
  [get_cells {current_code_reg[1]}]  \
  [get_cells {current_code_reg[7]}]  \
  [get_cells {current_code_reg[14]}]  \
  [get_cells {current_code_reg[15]}]  \
  [get_cells {current_code_reg[2]}]  \
  [get_cells {current_code_reg[24]}]  \
  [get_cells {current_code_reg[16]}]  \
  [get_cells {current_code_reg[5]}]  \
  [get_cells {current_code_reg[3]}]  \
  [get_cells {current_code_reg[10]}]  \
  [get_cells {current_code_reg[30]}]  \
  [get_cells {current_code_reg[29]}]  \
  [get_cells {current_code_reg[21]}]  \
  [get_cells {current_code_reg[26]}]  \
  [get_cells {current_code_reg[18]}]  \
  [get_cells {current_code_reg[4]}]  \
  [get_cells {current_code_reg[23]}]  \
  [get_cells {current_code_reg[22]}]  \
  [get_cells {current_code_reg[25]}]  \
  [get_cells {current_code_reg[11]}]  \
  [get_cells {current_code_reg[28]}]  \
  [get_cells {current_code_reg[6]}]  \
  [get_cells {current_code_reg[19]}]  \
  [get_cells {current_code_reg[12]}]  \
  [get_cells {current_code_reg[27]}]  \
  [get_cells {current_code_reg[8]}]  \
  [get_cells {current_code_reg[17]}] ] -to [list \
  [get_cells alert_reg]  \
  [get_cells {attempts_reg[1]}]  \
  [get_cells {current_code_reg[0]}]  \
  [get_cells {current_code_reg[31]}]  \
  [get_cells {lock_timer_reg[1]}]  \
  [get_cells {lock_timer_reg[2]}]  \
  [get_cells {lock_timer_reg[3]}]  \
  [get_cells {lock_timer_reg[4]}]  \
  [get_cells {lock_timer_reg[5]}]  \
  [get_cells {lock_timer_reg[9]}]  \
  [get_cells {lock_timer_reg[10]}]  \
  [get_cells {lock_timer_reg[11]}]  \
  [get_cells {lock_timer_reg[12]}]  \
  [get_cells {lock_timer_reg[13]}]  \
  [get_cells {lock_timer_reg[16]}]  \
  [get_cells {lock_timer_reg[17]}]  \
  [get_cells {lock_timer_reg[18]}]  \
  [get_cells unlocked_reg]  \
  [get_cells {lock_timer_reg[14]}]  \
  [get_cells {lock_timer_reg[6]}]  \
  [get_cells {lock_timer_reg[0]}]  \
  [get_cells {attempts_reg[0]}]  \
  [get_cells {lock_timer_reg[8]}]  \
  [get_cells {lock_timer_reg[7]}]  \
  [get_cells {lock_timer_reg[15]}]  \
  [get_cells locked_reg]  \
  [get_cells {current_code_reg[20]}]  \
  [get_cells {current_code_reg[13]}]  \
  [get_cells {current_code_reg[9]}]  \
  [get_cells {current_code_reg[1]}]  \
  [get_cells {current_code_reg[7]}]  \
  [get_cells {current_code_reg[14]}]  \
  [get_cells {current_code_reg[15]}]  \
  [get_cells {current_code_reg[2]}]  \
  [get_cells {current_code_reg[24]}]  \
  [get_cells {current_code_reg[16]}]  \
  [get_cells {current_code_reg[5]}]  \
  [get_cells {current_code_reg[3]}]  \
  [get_cells {current_code_reg[10]}]  \
  [get_cells {current_code_reg[30]}]  \
  [get_cells {current_code_reg[29]}]  \
  [get_cells {current_code_reg[21]}]  \
  [get_cells {current_code_reg[26]}]  \
  [get_cells {current_code_reg[18]}]  \
  [get_cells {current_code_reg[4]}]  \
  [get_cells {current_code_reg[23]}]  \
  [get_cells {current_code_reg[22]}]  \
  [get_cells {current_code_reg[25]}]  \
  [get_cells {current_code_reg[11]}]  \
  [get_cells {current_code_reg[28]}]  \
  [get_cells {current_code_reg[6]}]  \
  [get_cells {current_code_reg[19]}]  \
  [get_cells {current_code_reg[12]}]  \
  [get_cells {current_code_reg[27]}]  \
  [get_cells {current_code_reg[8]}]  \
  [get_cells {current_code_reg[17]}] ]
group_path -weight 1.000000 -name C2O -from [list \
  [get_cells alert_reg]  \
  [get_cells {attempts_reg[1]}]  \
  [get_cells {current_code_reg[0]}]  \
  [get_cells {current_code_reg[31]}]  \
  [get_cells {lock_timer_reg[1]}]  \
  [get_cells {lock_timer_reg[2]}]  \
  [get_cells {lock_timer_reg[3]}]  \
  [get_cells {lock_timer_reg[4]}]  \
  [get_cells {lock_timer_reg[5]}]  \
  [get_cells {lock_timer_reg[9]}]  \
  [get_cells {lock_timer_reg[10]}]  \
  [get_cells {lock_timer_reg[11]}]  \
  [get_cells {lock_timer_reg[12]}]  \
  [get_cells {lock_timer_reg[13]}]  \
  [get_cells {lock_timer_reg[16]}]  \
  [get_cells {lock_timer_reg[17]}]  \
  [get_cells {lock_timer_reg[18]}]  \
  [get_cells unlocked_reg]  \
  [get_cells {lock_timer_reg[14]}]  \
  [get_cells {lock_timer_reg[6]}]  \
  [get_cells {lock_timer_reg[0]}]  \
  [get_cells {attempts_reg[0]}]  \
  [get_cells {lock_timer_reg[8]}]  \
  [get_cells {lock_timer_reg[7]}]  \
  [get_cells {lock_timer_reg[15]}]  \
  [get_cells locked_reg]  \
  [get_cells {current_code_reg[20]}]  \
  [get_cells {current_code_reg[13]}]  \
  [get_cells {current_code_reg[9]}]  \
  [get_cells {current_code_reg[1]}]  \
  [get_cells {current_code_reg[7]}]  \
  [get_cells {current_code_reg[14]}]  \
  [get_cells {current_code_reg[15]}]  \
  [get_cells {current_code_reg[2]}]  \
  [get_cells {current_code_reg[24]}]  \
  [get_cells {current_code_reg[16]}]  \
  [get_cells {current_code_reg[5]}]  \
  [get_cells {current_code_reg[3]}]  \
  [get_cells {current_code_reg[10]}]  \
  [get_cells {current_code_reg[30]}]  \
  [get_cells {current_code_reg[29]}]  \
  [get_cells {current_code_reg[21]}]  \
  [get_cells {current_code_reg[26]}]  \
  [get_cells {current_code_reg[18]}]  \
  [get_cells {current_code_reg[4]}]  \
  [get_cells {current_code_reg[23]}]  \
  [get_cells {current_code_reg[22]}]  \
  [get_cells {current_code_reg[25]}]  \
  [get_cells {current_code_reg[11]}]  \
  [get_cells {current_code_reg[28]}]  \
  [get_cells {current_code_reg[6]}]  \
  [get_cells {current_code_reg[19]}]  \
  [get_cells {current_code_reg[12]}]  \
  [get_cells {current_code_reg[27]}]  \
  [get_cells {current_code_reg[8]}]  \
  [get_cells {current_code_reg[17]}] ] -to [list \
  [get_ports unlocked]  \
  [get_ports alert] ]
group_path -weight 1.000000 -name I2C -from [list \
  [get_ports clk]  \
  [get_ports rst]  \
  [get_ports {entered_code[31]}]  \
  [get_ports {entered_code[30]}]  \
  [get_ports {entered_code[29]}]  \
  [get_ports {entered_code[28]}]  \
  [get_ports {entered_code[27]}]  \
  [get_ports {entered_code[26]}]  \
  [get_ports {entered_code[25]}]  \
  [get_ports {entered_code[24]}]  \
  [get_ports {entered_code[23]}]  \
  [get_ports {entered_code[22]}]  \
  [get_ports {entered_code[21]}]  \
  [get_ports {entered_code[20]}]  \
  [get_ports {entered_code[19]}]  \
  [get_ports {entered_code[18]}]  \
  [get_ports {entered_code[17]}]  \
  [get_ports {entered_code[16]}]  \
  [get_ports {entered_code[15]}]  \
  [get_ports {entered_code[14]}]  \
  [get_ports {entered_code[13]}]  \
  [get_ports {entered_code[12]}]  \
  [get_ports {entered_code[11]}]  \
  [get_ports {entered_code[10]}]  \
  [get_ports {entered_code[9]}]  \
  [get_ports {entered_code[8]}]  \
  [get_ports {entered_code[7]}]  \
  [get_ports {entered_code[6]}]  \
  [get_ports {entered_code[5]}]  \
  [get_ports {entered_code[4]}]  \
  [get_ports {entered_code[3]}]  \
  [get_ports {entered_code[2]}]  \
  [get_ports {entered_code[1]}]  \
  [get_ports {entered_code[0]}]  \
  [get_ports {master_code[31]}]  \
  [get_ports {master_code[30]}]  \
  [get_ports {master_code[29]}]  \
  [get_ports {master_code[28]}]  \
  [get_ports {master_code[27]}]  \
  [get_ports {master_code[26]}]  \
  [get_ports {master_code[25]}]  \
  [get_ports {master_code[24]}]  \
  [get_ports {master_code[23]}]  \
  [get_ports {master_code[22]}]  \
  [get_ports {master_code[21]}]  \
  [get_ports {master_code[20]}]  \
  [get_ports {master_code[19]}]  \
  [get_ports {master_code[18]}]  \
  [get_ports {master_code[17]}]  \
  [get_ports {master_code[16]}]  \
  [get_ports {master_code[15]}]  \
  [get_ports {master_code[14]}]  \
  [get_ports {master_code[13]}]  \
  [get_ports {master_code[12]}]  \
  [get_ports {master_code[11]}]  \
  [get_ports {master_code[10]}]  \
  [get_ports {master_code[9]}]  \
  [get_ports {master_code[8]}]  \
  [get_ports {master_code[7]}]  \
  [get_ports {master_code[6]}]  \
  [get_ports {master_code[5]}]  \
  [get_ports {master_code[4]}]  \
  [get_ports {master_code[3]}]  \
  [get_ports {master_code[2]}]  \
  [get_ports {master_code[1]}]  \
  [get_ports {master_code[0]}]  \
  [get_ports {duress_code[31]}]  \
  [get_ports {duress_code[30]}]  \
  [get_ports {duress_code[29]}]  \
  [get_ports {duress_code[28]}]  \
  [get_ports {duress_code[27]}]  \
  [get_ports {duress_code[26]}]  \
  [get_ports {duress_code[25]}]  \
  [get_ports {duress_code[24]}]  \
  [get_ports {duress_code[23]}]  \
  [get_ports {duress_code[22]}]  \
  [get_ports {duress_code[21]}]  \
  [get_ports {duress_code[20]}]  \
  [get_ports {duress_code[19]}]  \
  [get_ports {duress_code[18]}]  \
  [get_ports {duress_code[17]}]  \
  [get_ports {duress_code[16]}]  \
  [get_ports {duress_code[15]}]  \
  [get_ports {duress_code[14]}]  \
  [get_ports {duress_code[13]}]  \
  [get_ports {duress_code[12]}]  \
  [get_ports {duress_code[11]}]  \
  [get_ports {duress_code[10]}]  \
  [get_ports {duress_code[9]}]  \
  [get_ports {duress_code[8]}]  \
  [get_ports {duress_code[7]}]  \
  [get_ports {duress_code[6]}]  \
  [get_ports {duress_code[5]}]  \
  [get_ports {duress_code[4]}]  \
  [get_ports {duress_code[3]}]  \
  [get_ports {duress_code[2]}]  \
  [get_ports {duress_code[1]}]  \
  [get_ports {duress_code[0]}]  \
  [get_ports reset_code_button]  \
  [get_ports {new_code[31]}]  \
  [get_ports {new_code[30]}]  \
  [get_ports {new_code[29]}]  \
  [get_ports {new_code[28]}]  \
  [get_ports {new_code[27]}]  \
  [get_ports {new_code[26]}]  \
  [get_ports {new_code[25]}]  \
  [get_ports {new_code[24]}]  \
  [get_ports {new_code[23]}]  \
  [get_ports {new_code[22]}]  \
  [get_ports {new_code[21]}]  \
  [get_ports {new_code[20]}]  \
  [get_ports {new_code[19]}]  \
  [get_ports {new_code[18]}]  \
  [get_ports {new_code[17]}]  \
  [get_ports {new_code[16]}]  \
  [get_ports {new_code[15]}]  \
  [get_ports {new_code[14]}]  \
  [get_ports {new_code[13]}]  \
  [get_ports {new_code[12]}]  \
  [get_ports {new_code[11]}]  \
  [get_ports {new_code[10]}]  \
  [get_ports {new_code[9]}]  \
  [get_ports {new_code[8]}]  \
  [get_ports {new_code[7]}]  \
  [get_ports {new_code[6]}]  \
  [get_ports {new_code[5]}]  \
  [get_ports {new_code[4]}]  \
  [get_ports {new_code[3]}]  \
  [get_ports {new_code[2]}]  \
  [get_ports {new_code[1]}]  \
  [get_ports {new_code[0]}]  \
  [get_ports confirm_reset] ] -to [list \
  [get_cells alert_reg]  \
  [get_cells {attempts_reg[1]}]  \
  [get_cells {current_code_reg[0]}]  \
  [get_cells {current_code_reg[31]}]  \
  [get_cells {lock_timer_reg[1]}]  \
  [get_cells {lock_timer_reg[2]}]  \
  [get_cells {lock_timer_reg[3]}]  \
  [get_cells {lock_timer_reg[4]}]  \
  [get_cells {lock_timer_reg[5]}]  \
  [get_cells {lock_timer_reg[9]}]  \
  [get_cells {lock_timer_reg[10]}]  \
  [get_cells {lock_timer_reg[11]}]  \
  [get_cells {lock_timer_reg[12]}]  \
  [get_cells {lock_timer_reg[13]}]  \
  [get_cells {lock_timer_reg[16]}]  \
  [get_cells {lock_timer_reg[17]}]  \
  [get_cells {lock_timer_reg[18]}]  \
  [get_cells unlocked_reg]  \
  [get_cells {lock_timer_reg[14]}]  \
  [get_cells {lock_timer_reg[6]}]  \
  [get_cells {lock_timer_reg[0]}]  \
  [get_cells {attempts_reg[0]}]  \
  [get_cells {lock_timer_reg[8]}]  \
  [get_cells {lock_timer_reg[7]}]  \
  [get_cells {lock_timer_reg[15]}]  \
  [get_cells locked_reg]  \
  [get_cells {current_code_reg[20]}]  \
  [get_cells {current_code_reg[13]}]  \
  [get_cells {current_code_reg[9]}]  \
  [get_cells {current_code_reg[1]}]  \
  [get_cells {current_code_reg[7]}]  \
  [get_cells {current_code_reg[14]}]  \
  [get_cells {current_code_reg[15]}]  \
  [get_cells {current_code_reg[2]}]  \
  [get_cells {current_code_reg[24]}]  \
  [get_cells {current_code_reg[16]}]  \
  [get_cells {current_code_reg[5]}]  \
  [get_cells {current_code_reg[3]}]  \
  [get_cells {current_code_reg[10]}]  \
  [get_cells {current_code_reg[30]}]  \
  [get_cells {current_code_reg[29]}]  \
  [get_cells {current_code_reg[21]}]  \
  [get_cells {current_code_reg[26]}]  \
  [get_cells {current_code_reg[18]}]  \
  [get_cells {current_code_reg[4]}]  \
  [get_cells {current_code_reg[23]}]  \
  [get_cells {current_code_reg[22]}]  \
  [get_cells {current_code_reg[25]}]  \
  [get_cells {current_code_reg[11]}]  \
  [get_cells {current_code_reg[28]}]  \
  [get_cells {current_code_reg[6]}]  \
  [get_cells {current_code_reg[19]}]  \
  [get_cells {current_code_reg[12]}]  \
  [get_cells {current_code_reg[27]}]  \
  [get_cells {current_code_reg[8]}]  \
  [get_cells {current_code_reg[17]}] ]
group_path -weight 1.000000 -name I2O -from [list \
  [get_ports clk]  \
  [get_ports rst]  \
  [get_ports {entered_code[31]}]  \
  [get_ports {entered_code[30]}]  \
  [get_ports {entered_code[29]}]  \
  [get_ports {entered_code[28]}]  \
  [get_ports {entered_code[27]}]  \
  [get_ports {entered_code[26]}]  \
  [get_ports {entered_code[25]}]  \
  [get_ports {entered_code[24]}]  \
  [get_ports {entered_code[23]}]  \
  [get_ports {entered_code[22]}]  \
  [get_ports {entered_code[21]}]  \
  [get_ports {entered_code[20]}]  \
  [get_ports {entered_code[19]}]  \
  [get_ports {entered_code[18]}]  \
  [get_ports {entered_code[17]}]  \
  [get_ports {entered_code[16]}]  \
  [get_ports {entered_code[15]}]  \
  [get_ports {entered_code[14]}]  \
  [get_ports {entered_code[13]}]  \
  [get_ports {entered_code[12]}]  \
  [get_ports {entered_code[11]}]  \
  [get_ports {entered_code[10]}]  \
  [get_ports {entered_code[9]}]  \
  [get_ports {entered_code[8]}]  \
  [get_ports {entered_code[7]}]  \
  [get_ports {entered_code[6]}]  \
  [get_ports {entered_code[5]}]  \
  [get_ports {entered_code[4]}]  \
  [get_ports {entered_code[3]}]  \
  [get_ports {entered_code[2]}]  \
  [get_ports {entered_code[1]}]  \
  [get_ports {entered_code[0]}]  \
  [get_ports {master_code[31]}]  \
  [get_ports {master_code[30]}]  \
  [get_ports {master_code[29]}]  \
  [get_ports {master_code[28]}]  \
  [get_ports {master_code[27]}]  \
  [get_ports {master_code[26]}]  \
  [get_ports {master_code[25]}]  \
  [get_ports {master_code[24]}]  \
  [get_ports {master_code[23]}]  \
  [get_ports {master_code[22]}]  \
  [get_ports {master_code[21]}]  \
  [get_ports {master_code[20]}]  \
  [get_ports {master_code[19]}]  \
  [get_ports {master_code[18]}]  \
  [get_ports {master_code[17]}]  \
  [get_ports {master_code[16]}]  \
  [get_ports {master_code[15]}]  \
  [get_ports {master_code[14]}]  \
  [get_ports {master_code[13]}]  \
  [get_ports {master_code[12]}]  \
  [get_ports {master_code[11]}]  \
  [get_ports {master_code[10]}]  \
  [get_ports {master_code[9]}]  \
  [get_ports {master_code[8]}]  \
  [get_ports {master_code[7]}]  \
  [get_ports {master_code[6]}]  \
  [get_ports {master_code[5]}]  \
  [get_ports {master_code[4]}]  \
  [get_ports {master_code[3]}]  \
  [get_ports {master_code[2]}]  \
  [get_ports {master_code[1]}]  \
  [get_ports {master_code[0]}]  \
  [get_ports {duress_code[31]}]  \
  [get_ports {duress_code[30]}]  \
  [get_ports {duress_code[29]}]  \
  [get_ports {duress_code[28]}]  \
  [get_ports {duress_code[27]}]  \
  [get_ports {duress_code[26]}]  \
  [get_ports {duress_code[25]}]  \
  [get_ports {duress_code[24]}]  \
  [get_ports {duress_code[23]}]  \
  [get_ports {duress_code[22]}]  \
  [get_ports {duress_code[21]}]  \
  [get_ports {duress_code[20]}]  \
  [get_ports {duress_code[19]}]  \
  [get_ports {duress_code[18]}]  \
  [get_ports {duress_code[17]}]  \
  [get_ports {duress_code[16]}]  \
  [get_ports {duress_code[15]}]  \
  [get_ports {duress_code[14]}]  \
  [get_ports {duress_code[13]}]  \
  [get_ports {duress_code[12]}]  \
  [get_ports {duress_code[11]}]  \
  [get_ports {duress_code[10]}]  \
  [get_ports {duress_code[9]}]  \
  [get_ports {duress_code[8]}]  \
  [get_ports {duress_code[7]}]  \
  [get_ports {duress_code[6]}]  \
  [get_ports {duress_code[5]}]  \
  [get_ports {duress_code[4]}]  \
  [get_ports {duress_code[3]}]  \
  [get_ports {duress_code[2]}]  \
  [get_ports {duress_code[1]}]  \
  [get_ports {duress_code[0]}]  \
  [get_ports reset_code_button]  \
  [get_ports {new_code[31]}]  \
  [get_ports {new_code[30]}]  \
  [get_ports {new_code[29]}]  \
  [get_ports {new_code[28]}]  \
  [get_ports {new_code[27]}]  \
  [get_ports {new_code[26]}]  \
  [get_ports {new_code[25]}]  \
  [get_ports {new_code[24]}]  \
  [get_ports {new_code[23]}]  \
  [get_ports {new_code[22]}]  \
  [get_ports {new_code[21]}]  \
  [get_ports {new_code[20]}]  \
  [get_ports {new_code[19]}]  \
  [get_ports {new_code[18]}]  \
  [get_ports {new_code[17]}]  \
  [get_ports {new_code[16]}]  \
  [get_ports {new_code[15]}]  \
  [get_ports {new_code[14]}]  \
  [get_ports {new_code[13]}]  \
  [get_ports {new_code[12]}]  \
  [get_ports {new_code[11]}]  \
  [get_ports {new_code[10]}]  \
  [get_ports {new_code[9]}]  \
  [get_ports {new_code[8]}]  \
  [get_ports {new_code[7]}]  \
  [get_ports {new_code[6]}]  \
  [get_ports {new_code[5]}]  \
  [get_ports {new_code[4]}]  \
  [get_ports {new_code[3]}]  \
  [get_ports {new_code[2]}]  \
  [get_ports {new_code[1]}]  \
  [get_ports {new_code[0]}]  \
  [get_ports confirm_reset] ] -to [list \
  [get_ports unlocked]  \
  [get_ports alert] ]
set_clock_gating_check -setup 0.0 
set_wire_load_mode "enclosed"
