
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:31:32 IST (Jun 20 2025 05:01:32 UTC)

// Verification Directory fv/down_counter_4bit 

module down_counter_4bit(clk, rst, count);
  input clk, rst;
  output [3:0] count;
  wire clk, rst;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_11, n_12, n_15;
  DFFQX4 \count_reg[2] (.CK (clk), .D (n_11), .Q (count[2]));
  OAI221XL g139(.A0 (count[3]), .A1 (n_9), .B0 (n_0), .B1 (n_8), .C0
       (n_1), .Y (n_12));
  OR2X1 g141(.A (rst), .B (n_15), .Y (n_11));
  DFFHQX8 \count_reg[1] (.CK (clk), .D (n_7), .Q (count[1]));
  INVXL g142(.A (n_8), .Y (n_9));
  OR2X1 g146(.A (rst), .B (n_4), .Y (n_7));
  NOR2BXL g145(.AN (n_5), .B (count[2]), .Y (n_8));
  XNOR2X1 g149(.A (count[0]), .B (count[1]), .Y (n_4));
  OR2X1 g150(.A (rst), .B (n_2), .Y (n_3));
  NOR2BXL g151(.AN (n_2), .B (count[1]), .Y (n_5));
  INVXL g152(.A (rst), .Y (n_1));
  DFFX2 \count_reg[0] (.CK (clk), .D (n_3), .Q (count[0]), .QN (n_2));
  DFFX2 \count_reg[3] (.CK (clk), .D (n_12), .Q (count[3]), .QN (n_0));
  XOR2X4 g2(.A (count[2]), .B (n_5), .Y (n_15));
endmodule

