
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:46:55 IST (Jun 20 2025 05:16:55 UTC)

// Verification Directory fv/up_counter_4bit 

module up_counter_4bit(clk, rst, count);
  input clk, rst;
  output [3:0] count;
  wire clk, rst;
  wire [3:0] count;
  wire \count[1]_29 , \count[2]_30 , \count[3]_31 , n_1, n_3, n_5, n_6,
       n_9;
  wire n_12;
  EDFFTRX4 \count_reg[3] (.CK (clk), .D (\count[3]_31 ), .E (n_6), .RN
       (n_9), .Q (count[3]), .QN (\count[3]_31 ));
  DFFTRX4 \count_reg[2] (.CK (clk), .D (n_9), .RN (n_12), .Q
       (count[2]), .QN (\count[2]_30 ));
  DFFTRX4 \count_reg[1] (.CK (clk), .D (n_9), .RN (n_5), .Q (count[1]),
       .QN (\count[1]_29 ));
  NOR2BXL g87(.AN (n_1), .B (\count[2]_30 ), .Y (n_6));
  XNOR2X1 g90(.A (count[1]), .B (n_3), .Y (n_5));
  DFFTRX4 \count_reg[0] (.CK (clk), .D (n_9), .RN (n_3), .Q (count[0]),
       .QN (n_3));
  NOR2BXL g91(.AN (count[0]), .B (\count[1]_29 ), .Y (n_1));
  INVXL g93(.A (rst), .Y (n_9));
  XOR2X4 g2(.A (count[2]), .B (n_1), .Y (n_12));
endmodule

