
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:46:55 IST (Jun 20 2025 05:16:55 UTC)

// Verification Directory fv/up_counter_4bit 

module up_counter_4bit(clk, rst, count);
  input clk, rst;
  output [3:0] count;
  wire clk, rst;
  wire [3:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, \count[1]_29 , \count[2]_30 , \count[3]_31 , n_1;
  wire n_2, n_3, n_5, n_6, n_8, n_9;
  EDFFTRX4 \count_reg[3] (.CK (clk), .D (\count[3]_31 ), .E (n_6), .RN (n_9), .Q (UNCONNECTED), .QN (\count[3]_31 ));
  DFFTRX4 \count_reg[2] (.CK (clk), .D (n_9), .RN (n_8), .Q (UNCONNECTED0), .QN (\count[2]_30 ));
  DFFTRX4 \count_reg[1] (.CK (clk), .D (n_9), .RN (n_5), .Q (UNCONNECTED1), .QN (\count[1]_29 ));
  XNOR2X1 g85(.A (count[2]), .B (n_2), .Y (n_8));
  NOR2BXL g87(.AN (n_1), .B (\count[2]_30 ), .Y (n_6));
  XNOR2X1 g90(.A (count[1]), .B (n_3), .Y (n_5));
  DFFTRX4 \count_reg[0] (.CK (clk), .D (n_9), .RN (n_3), .Q (count[0]), .QN (UNCONNECTED2));
  INVXL g88(.A (n_1), .Y (n_2));
  NOR2BXL g91(.AN (count[0]), .B (\count[1]_29 ), .Y (n_1));
  INVXL g95(.A (\count[3]_31 ), .Y (count[3]));
  INVXL g93(.A (rst), .Y (n_9));
  INVXL g96(.A (count[0]), .Y (n_3));
  INVXL g92(.A (\count[1]_29 ), .Y (count[1]));
  INVXL g94(.A (\count[2]_30 ), .Y (count[2]));
endmodule

