
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:43:01 IST (Jun 20 2025 05:13:01 UTC)

// Verification Directory fv/mux4to1 

module mux4to1(in, sel, y);
  input [3:0] in;
  input [1:0] sel;
  output y;
  wire [3:0] in;
  wire [1:0] sel;
  wire y;
  wire n_0, n_1, n_2, n_3;
  MXI4XL g135(.A (n_3), .B (n_1), .C (n_0), .D (n_2), .S0 (sel[1]), .S1 (sel[0]), .Y (y));
  INVXL g136(.A (in[0]), .Y (n_3));
  INVXL g137(.A (in[3]), .Y (n_2));
  INVXL g138(.A (in[2]), .Y (n_1));
  INVXL g139(.A (in[1]), .Y (n_0));
endmodule

