
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 10:43:01 IST (Jun 20 2025 05:13:01 UTC)

// Verification Directory fv/mux4to1 

module mux4to1(in, sel, y);
  input [3:0] in;
  input [1:0] sel;
  output y;
  wire [3:0] in;
  wire [1:0] sel;
  wire y;
  MX4X4 g2(.A (in[0]), .B (in[2]), .C (in[1]), .D (in[3]), .S0
       (sel[1]), .S1 (sel[0]), .Y (y));
endmodule

